- project.godot
Previously you could move the player with the controller, but not interact with NPCs.
Add the bottom joypad button to the ui_accept action, which we are currently overloading for interaction (but may also in future want to use for menus anyway).
> Bind joypad bottom button (xbox A) to interaction

- scenes/player/player.tscn
Previously, if the player is positioned such that its InteractRay starts inside an NPC's InteractArea, the ray would not be considered to have collided with the NPC so the interaction would not be offered. This can happen because we are faking perspective by giving NPCs (and the player) two hitboxes: one for collisions around the feet, and one for interactions in the player's line of sight.
Enable RayCast2D.hit_from_inside on the player's interact ray.
> Player: Enable hit_from_inside on interact ray

- .github/workflows/checks.yaml
- .pre-commit-config.yaml
- scenes/interact_area.gd
- scenes/interact_label.gd
- scenes/interact_ray.gd
- scenes/npcs/npc.gd
- scenes/npcs/talker/talker.gd
- scenes/player/player.gd
- scenes/player/player_interaction.gd
- scenes/player/player_sprite.gd
This PR reformats the GDScript source files with `gdformat`, and adjusts some declarations to pass `gdlint` and match the [GDScript style guide](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html). The diff is pleasingly small, perhaps because there's not much code yet.
It then adds a pre-commit config file to run these checks locally, and sets up a GitHub Actions workflow to run the pre-commit checks on pull requests.
> Add linting with gdlint and gdformat, run via pre-commit and CI

- scenes/music_puzzle/music_puzzle.gd
This is now a `@tool` script so that a configuration warning can be issued if the number of melodies doesn't match the number of bonfires. But as a result, opening this scene in the editor previously issued this warning:
ERROR: res://scenes/music_puzzle/music_puzzle.gd:22 - Invalid access to property or key 'note_played' on a base object of type 'Node2D (MusicalRockXylophone)'.
This is because MusicalRockXylophone is not a `@tool`.
Guard the signal connection with Engine.is_editor_hint().
> MusicPuzzle: Don't listen to xylophone when running in editor

- .editorconfig
This is the Godot editor's default, but Zed doesn't know that.
> editorconfig: Configure *.gd files to use tabs for indentation

- .github/workflows/github-pages.yml
In https://github.com/endlessm/amalgamate-pages/releases/tag/v1.0.3 the amalgamate-pages action was updated to not show builds for branches which have been deleted. In the case where the branch was deleted due to a PR being merged, the workflow will end up being run anyway due to the new build on `main`, but this might happen before the branch is deleted; and a branch may also be deleted without having been merged.
Run the workflow when a branch is deleted so that any corresponding web build is removed.
> ci: Rebuild GitHub Pages when a branch is deleted

- default_bus_layout.tres
- scenes/music_puzzle/musical_rock.tscn
Having separate audio buses allows us to change the volume of all the audio that plays in that bus independently. It also allows adding effects to the buses, but we probably won't even use that. However, I think having at least 2 basic buses for Music and Audio, and have all AudioStreamPlayers use one of them (or a new bus inherited from one of them), would be a good start since that lets us have 2 sliders in the config menu: one for music and one for sound effects.
> Create 2 basic audio buses: Music & SFX

- scenes/music_puzzle/music_puzzle.gd
- scenes/music_puzzle/musical_rock.gd
- scenes/music_puzzle/musical_rock_xylophone.gd
This squashes warnings that are shown in the debugger tab when running the game from the editor.
I have tried to find a way to check for these warnings in CI but it seems hard to do. If I adjust project.godot to make these warnings fatal rather than warnings, it blocks running the project (really annoying in development) or exporting it.
The alternative seems to be to write a CLI tool that feeds the source files into Godot's LSP server and extracts the diagnostics. Overkill.
> Add explicit type annotations

- project.godot
See here:
https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#class-projectsettings-property-rendering-2d-snap-snap-2d-transforms-to-pixel
It's a subtle change, but it should reduce some artifacts that you may see when working with pixel art, like for instance, tiles in tilemaps not quite fitting together, blurry lines, and stuff like that.
> Enable 2D pixel snapping for crisper pixel art look

- scenes/world_map/frays_end.tscn
- scenes/world_map/song_sanctuaries.tscn
The Player scene has a label that is shown when an interaction is available. This label is reparented to the current scene's "ScreenOverlay" node. However, the Frays End and Song Sanctuaries scenes did not have a ScreenOverlay node, causing the label to be displayed at an incorrect position (or not visibly at all).
Add a ScreenOverlay node to each scene.
> world_map: Add ScreenOverlay CanvasLayer nodes

- project.godot
- scenes/game_state/game_state.gd
- scenes/game_state/game_state.gd.uid
- scenes/game_state/game_state.tscn
- scenes/inventory/inventory.gd
- scenes/inventory/inventory.gd.uid
- scenes/inventory/inventory_item.gd
- scenes/inventory/inventory_item.gd.uid
- scenes/world_map/song_sanctuaries.tscn
After some back and forth with @JuanFdS, we came up with an approach that we believe is user friendly for the Learners, if they need to use global state.
We have a global scene called GameState which, at the moment, only has an "inventory", which in turn has "items". We thought that this results in code-as-documentation, where you can know what kind of global state there's by looking into the code of game_state.gd.
Items can be created as resources and they can be, for the time being, of any of the three types: Memory, Imagination, or Spirit.
The global scene can be edited using godot inspector, which can be useful to test different states.
As for persistance, there's none at the moment (other than editing the scene manually, which is fixed at compiled time). But in the future, a …
> Simple global state to store Items (for now)

- project.godot
- scenes/intro/intro.dialogue
- scenes/intro/intro.dialogue.import
- scenes/intro/intro.gd
- scenes/intro/intro.tscn
Previously, a one-line placeholder introduction to the world was displayed by animating the visible_ratio property of a RichTextLabel.
Instead, define the on-screen introduction text as a dialogue file. Trigger the fade-out animation with a mutation (a.k.a. method call) in the dialogue file. Replace the RichTextLabel with an invocation of that dialogue.
https://github.com/endlessm/threadbare/issues/6
> intro: Replace placeholder text with dialogue

- scenes/player/player.gd
Previously, the horizontal and vertical axes were fetched separately as a float between -1 and 1, and then combined into a Vector2. In the case where the player is pressing right and down, the resulting vector will be (1, 1), which has length sqrt(2) ≈ 1.4. This means that the player can move faster on the diagonal than horizontally or vertically.
Instead, use Input.get_vector(), which returns a unit vector based on the four actions provided. This means the player moves the same speed regardless of which direction they're walking/running in.
> player: Use unit-length input vector

- project.godot
This binds B to ui_cancel (which skips to the end of the current dialogue line, for the impatient) and LB to run.
It also adjusts the ui_accept binding to only match joypad device 0, in common with all the other joypad mappings. Arguably for a single-player game we could allow input from any connected joypad, but we should be at least be consistent.
> Add joypad mappings for running and skipping dialogue

- scenes/intro/intro.dialogue
I had included [next=auto] directives at the end of each line of the introduction so that the intro text would advance automatically after a few moments (proportional to the length of the text).
What I had not appreciated is that if you configure the text to advance automatically, the player can't press ui_accept (space/A) to move forward more quickly. This is annoying if you want to skip the introduction.
Remove these directives.
> intro: Remove [next=auto] directives

- scenes/enemies/guard/guard.gd
It can be played here: https://endlessm.github.io/threadbare/#stealth_level/stealth_level
Having a reference to an editor's only type causes errors on release build. Changed the code so it dynamically finds the node.
Directly referencing a node like EditorInterface can only be done in plugins and scripts that only runs in the editor.
> Fix #79: stealth level is broken on release builds

- .github/workflows/export.yml
This maintenance release was made a couple of days ago. In particular this should fix a shader bug in the web export that manuq ran into when experimenting with deforming the floor as if made of fabric.
https://godotengine.org/article/maintenance-release-godot-4-4-1/ https://github.com/godotengine/godot/pull/103878#issuecomment-2715164989 https://github.com/endlessm/threadbare/issues/10#issuecomment-2715238382
> ci: Export with Godot 4.4.1

- project.godot
Previously, we had configured the project such that the following code would raise a warning that the type was being inferred rather than explicitly specified:
var sprite := Sprite2D.new()
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/static_typing.html#warning-system says:
> Additionally, you can enable the INFERRED_DECLARATION warning if you
> prefer a more readable and reliable, but more verbose syntax.
While it's nice to spell out the types of variables in some cases – particularly top-level fields of a class – my feeling is that writing out the type of every variable in a function is often less readable. Sadly there is no way to enable this warning only for top-level fields.
Disable this warning, allowing variables to have an inferred type when initialised with …
> Disable INFERRED_DECLARATION warning

- AUTHORS
- COPYING
- README.md
This is a soft copyleft license, which allows combining this project with closed-source parts (such as, hypothetically, console ports of Godot) while still requiring the source to this project itself to be made available to those who receive an executable build of the game.
Add the license as a COPYING file. Explain in the README that this applies to original code, and not to third-party assets and addons. (The only addon at present is under the MIT license.)
Add a license header to all source files.
> Apply MPL-2.0 license to original code

- .github/workflows/checks.yaml
- scenes/ink_combat/ink_combat.gd
When I added a job that runs `reuse lint`, I piped its output to `tee $GITHUB_STEP_SUMMARY` so that the output shows up in a nicely-formatted way in the workflow run summary.
Unfortunately, by default the exit status of a shell pipeline is the exit status of the rightmost command. This means that even if `reuse lint` fails, the pipeline will succeed, erroneously claiming that the licensing information is correctly specified.
Use bash's pipefail option to cause the pipeline to fail in this case.
> ci: Report errors from `reuse lint`

- scenes/interact/interact_area.gd
- scenes/music_puzzle/musical_rock.gd
- scenes/npcs/talker/talker.gd
- scenes/player/player_interaction.gd
When the player start interaction signal is emitted, it also tells if it's interacting from the right side. Then the Talker NPC saves the previous facing direction, and faces the player while the interaction happens.
Adjust the music rocks which also use the interaction to ignore the parameter.
> Talker: Look at player when interacting

- REUSE.toml
- assets/midjourney/embroidered-world-map.webp.license
- scenes/ink_combat/big_splash/big_splash.gd
- scenes/ink_combat/ink_blob/ink_blob.gd
- scenes/ink_combat/ink_drinker/ink_drinker.gd
- scenes/ink_combat/inkwell/inkwell.gd
- scenes/ink_combat/player/animation_player.gd
- scenes/ink_combat/player/player.gd
- scenes/ink_combat/player/player_fighting.gd
- scenes/ink_combat/player/player_sprite.gd
- scenes/ink_combat/splash/splash.gd
- scenes/player/animation_player.gd
- scenes/scene_switcher/scene_switcher.gd
- scenes/transitions/transition_layer.gdshader
- scenes/transitions/transitions.gd
- scenes/world_map/story_quest_starter.gd
Previously, the codebase was inconsistent. Some files used:
SPDX-FileCopyrightText: 2025 The Threadbare Authors
while others used:
SPDX-FileCopyrightText: The Threadbare Authors
As argued in https://daniel.haxx.se/blog/2023/01/08/copyright-without-years/ there is no strict need to include the year in copyright notices – the information is present in the Git commit history. And excluding the year means that there is no need to think about bumping the upper bound of the range each time a file is modified in a new year.
Remove the year from first-party copyright notices.
> Remove date from first-party FileCopyrightText notices

- project.godot
- scenes/globals/pause.gd
- scenes/globals/pause.gd.uid
- scenes/player/player.gd
- scenes/player/player_fighting.gd
- scenes/player/player_interaction.gd
- scenes/scene_switcher/scene_switcher.gd
Previously, if the player continues to hold a direction during the transition, the character would be moved in the new scene. This could lead to the character ending up in an unexpected location on the other side of the transition – perhaps even off the edge of the scene.
To solve this issue, and to move forward in adding all the systems that the game needs to function, a Pause System has been added, and it is used during scene transitions.
The Pause System allows pausing the whole game, or just the player input, and is flexible enough to allow adding other kinds of pauses. It also supports being requested pauses from a multitude of different origins, and handling it gracefully. This pattern of requests prevents some bugs that could appear if the pause logic becomes more complex. For …
> Added Pause System

- project.godot
scenes/stealth_level/stealth_level_challenge_complete.dialogue was removed in commit bb68c70b8c84293de0560cb882c7cc9fc6ec7a8f ("Added collectibles to music puzzle and stealth level") because the NPC in question was replaced by a collectible item.
Remove it from the translations_pot_files list.
> project: Remove reference to deleted dialogue file

- project.godot
- scenes/player/player.gd
- scenes/player/player.tscn
- scenes/player/player_controller.gd
- scenes/player/player_controller.gd.uid
- scenes/player/player_fighting.gd
- scenes/player/player_interaction.gd
Since we need to be able to pause the inputs of a player, a Player Controller has been added as an intermediary between the Input singleton and the player scripts. This controller checks if the input has been paused, and if so, ignores them.
Player Controllers are also a good practice in general, since they allow to easily have player characters that are controlled by entities that are not input, like code for cinematics, or another player through multiplayer.
> Adding a Player Controller

- scenes/ui/dialogue/theme.tres
The main balloon is surrounded by a Panel, which the theme inherited from Godot Dialogue Manager's default balloon scene previously specified to be a StyleBoxFlat with a rounded border.
Replace that style with a 9-patch banner texture from Tiny Swords, with the stretch mode set to tile (it's pixel art!) and its margins fudged a little so that the whole box fits on the screen. There is a bit of a weird interaction with the MarginContainer within - perhaps the margins on that should be tweaked instead – but this looks a lot better already.
The buttons for dialogue choices are still in the default GDM style as of this commit.
Helps https://github.com/endlessm/threadbare/issues/54
----
I ran out of time today to style the buttons for dialogue choices but IMO this is already a nice …
> dialogue: Use Tiny Swords banner asset for main balloon

- scenes/ui/dialogue/theme.tres
- scenes/world_map/story_quest_starter.dialogue
As previously, the "hover" and "normal" states are the same - the hover
state is not really used because the code automatically focuses the
button when the mouse enters it, and the focus state is drawn on top of
any other state.
Unselected buttons are blue. The focused item is yellow with a bright
yellow border.
While we don't currently use this GDM feature, it's possible to have a
dialogue choice shown but not available, in which case the button is
disabled. Style the disabled state consistently with the others in case
we need this later.
<https://github.com/nathanhoad/godot_dialogue_manager/blob/main/docs/Basic_Dialogue.md#responses>
Similarly, the "pressed" state is not used, but if we later introduced
toggle buttons somewhere else it might be nice to have that.
Helps …
> Style dialogue buttons

- scenes/player/player_interaction.gd
- scenes/props/fixed_size_label/fixed_size_label.gd
Fix regression when changing the interact label by the fixed size label in 3aa25d56.
Setting visibility to the new label doesn't hide the label container because it may have been reparented to the ScreenOverlay node.
So, add a generic object setter to the FixedSizeLabel and check if the property being set is the visibility. If so, set the label container visibility to the same value.
Fix https://github.com/endlessm/threadbare/issues/113
> Fixed size label: Fix visibility

- scenes/player/player.gd
- scenes/player/player_interaction.gd
- scenes/props/fixed_size_label/fixed_size_label.gd
Also, make Fixed Size Label hide or show the label that it places on the ScreenOverlay based on whether it is visible in the tree or not.
https://github.com/user-attachments/assets/d3aec36e-88fe-43dc-b553-1372b40071b0
> Change player's behavior node visibility when it changes mode

- scenes/player/player.gd
- scenes/player/player_interaction.gd
- scenes/props/fixed_size_label/fixed_size_label.gd
- scenes/props/fixed_size_label/fixed_size_label.tscn
- scenes/ui/theme.tres
Set FixedSizeLabel font to m6x11plus pixel font.
Also, removed different places where the size of the label's font was being modified, and left only one: the theme.
Finally, added a custom type to the newly created theme that is specific for FixedSizeLabel
Branched from https://github.com/endlessm/threadbare/pull/132 , so please review that one first.
> Fix 130 interact label doesnt use pixel art font

- scenes/player/player_attack_01.png.license
- scenes/player/player_attack_02.png.license
- scenes/player/player_idle.png.license
- scenes/player/player_walk.png.license
According to the README, hreadbare's original assets are covered by Creative Commons Attribution-ShareAlike 4.0 International.
> Fix license of player assets

- scenes/game_elements/props/teleporter/teleporter/components/teleporter.gd
- scenes/globals/property_utils.gd
- scenes/globals/property_utils.gd.uid
- scenes/globals/scene_switcher/scene_switcher.gd
- scenes/globals/scene_switcher/transitions/transitions.gd
- scenes/globals/scene_switcher/transitions/transitions.tscn
- scenes/world_map/frays_end.tscn
- scenes/world_map/song_sanctuaries.tscn
Two issues have been grouped into this PR because they are closely related.
Three properties have been added to the teleporters. A boolean specifying if the teleporter should use transitions, and a couple of properties to specify an enter_transition and an exit_transition. These properties only appear when the "use_transition" boolean is true.
This PR also sets up transitions of Frays End and Song Sanctuaries teleporters so they match the players movement direction.
Fixes #69 
Fixes #67
> Added transition properties to teleporters and setup transitions in Frays End and Song Sanctuaries

- scenes/globals/property_utils.gd
String.capitalize() already replaces underscores with spaces.
https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-capitalize
> PropertyUtils: Improve get_enum_hint_string

- .pre-commit-config.yaml
SVG files are, technically speaking, text files; but spiritually they are image files that are generally edited with specialised tools rather than with a text editor.
In particular, it is common for SVG files not to have a trailing newline, and it seems cruel to force artists & developers to add one by hand.
Exclude .svg files from trailing-whitespace and newline checks.
> pre-commit: Exclude SVG files from whitespace checks

- scenes/game_elements/characters/npcs/story_quest_starter/components/story_quest_starter.gd
- scenes/globals/scene_switcher/scene_switcher.gd
- scenes/menus/intro/components/intro.gd
When testing the game, the abrupt scene-switches at the end of the world map and when entering a quest feel bad, particularly compared to other scene transitions.
Add fade transitions.
The splash-to-intro transition is a bit trickier for reasons that I will explain in a subsequent PR, so is not covered here.
> Add fade transitions between intro, world map, and quest

- scenes/game_elements/characters/player/components/player_interaction.gd
- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/musical_rock.gd
Previously, the rock interaction lasted as long as the sound effect. This was annoying because the player was frozen on the spot for the whole sound effect, rather than being able to move to the next note.
Don't await the end of the sound effect before ending the interaction.
Helps #112
----
Someone mentioned this in the playtest today; I can't find it in the notes but I think it makes the puzzle feel better. Making this change required fixing a latent bug in PlayerInteraction.
> MusicalRock: End interaction immediately, while sound plays

- scenes/game_elements/characters/player/components/player_interaction.gd
Previously, it was possible to trigger an interaction while changing scene. For example, when you interact with an NPC and choose to start a quest, the interaction ending triggers a scene transition. However, during this 1-second transition, the player character is (by definition) in the correct position to trigger an interaction with the NPC, so the “Talk” prompt was re-displayed and pressing ui_accept quickly enough would cause the dialogue to begin again.
The first part needs special handling to not display the interact label when inputs are paused: use PlayerController.inputs_paused() to detect this case and hide the label if it would otherwise be displayed.
The second part is because the input handling used PlayerController.is_action_just_released() rather than …
> PlayerInteraction: Disable when inputs are paused

- scenes/game_elements/props/buildings/castle/castle.tscn
- scenes/game_elements/props/buildings/house/house_1.tscn
- scenes/game_elements/props/buildings/house/house_2.tscn
- scenes/game_elements/props/buildings/tower/tower.tscn
- scenes/game_elements/props/sign/sign.tscn
- scenes/game_elements/props/tree/tree.tscn
All these elements are game elements that the player should collide with. Set them all to the collision layer 5 (walls) and, if they had collision mask 1, removed it since it's redundant.
Fixes https://github.com/endlessm/threadbare/issues/156
> Fix several game elements collisions

- scenes/menus/intro/components/intro.gd
- scenes/menus/splash/components/splash.gd
- scenes/menus/splash/splash.tscn
Previously, when the splash screen was complete (either due to 5 seconds passing from the end of the animation, or the player pressing a key), the scene would be switched abruptly to the intro, without any transition.
Add a fade.
Compared to #152 there are a few more details here to deal around avoiding double-transitioning and delaying the start of the intro dialogue until the fade is complete.
> Fade from splash to intro narrative

- project.godot
- scenes/globals/pause/pause_overlay.gd
- scenes/globals/pause/pause_overlay.gd.uid
- scenes/globals/pause/pause_overlay.tscn
- scenes/ui_elements/shared_components/theme.tres
A simple scene that pauses the game when the user presses escape. It's globally available, so it works in all scenes.
Also: Changed the default font of the theme, so it can be used for labels.
Fixes #170
> Add Pause Overlay as a Global Scene

- scenes/game_elements/props/tree/components/wind_affected_material.tres
- scenes/game_elements/props/tree/tree.gdshader
- scenes/game_elements/props/tree/tree.gdshader.uid
- scenes/game_elements/props/tree/tree.tscn
The trees now have a material that has a shader that simulates wind.
It's done through a fragment shader that offsets the texture sampling based on time and some parameters.
The material also has a noise to define a "wind map" so that trees close to each other have similar wind conditions but there is some variability in the movement. Some parameters are also considered, like max_wind_speed and max_wind_intensity. Those parameters could be increased to simulate a quiet breeze, or a strong gust.
> Add a wind shader to the trees

- scenes/game_elements/props/tree/tree.gdshader
There was a bug in the wind shader where large positions would all resolve to the same noise value, making the trees move at unison in those cases.
Instead of using the raw world position as a UV coordinate for the noise texture, we should use its fractional part so it remains between 0 and 1.
> Fix wind shader calculations for large positions

- scenes/game_elements/characters/npcs/shared_components/npc.gd
- scenes/game_elements/characters/npcs/talker/components/talker.gd
- scenes/game_elements/characters/player/components/player.gd
- scenes/game_elements/characters/player/components/player_sprite.gd
- scenes/game_elements/props/sign/components/sign.gd
- scenes/game_elements/props/spawn_point/components/spawn_point.gd
- scenes/globals/enums.gd
- scenes/globals/enums.gd.uid
- scenes/world_map/frays_end.tscn
- scenes/world_map/song_sanctuaries.tscn
This commit adds a player direction to the spawn point. When set to other than "UNSPECIFIED", it will change the player look at direction to either left or right.
When players teleport from one scene to the other, sometimes it looks weird if the player looks in the opposite direction. This solves that issue by allowing to specify the look direction in the spawn point.
> Add a player direction to spawn point

- project.godot
- scenes/game_elements/characters/npcs/story_quest_starter/components/story_quest_starter.dialogue
- scenes/game_elements/characters/npcs/talker/components/default.dialogue
- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/dialogues/musician.dialogue
- scenes/quests/lore_quests/quest_001/3_stealth_level/components/dialogues/stealth_level_elder_intro.dialogue
Previously a mixture of ‘StoryWeaver’ and ‘Storyweaver’ was used.
While the SpongeBob style is not to my taste, that is the capitalization used in the game's design documents. Consistently spell the protagonist's name as ‘StoryWeaver’.
> Consistently capitalize ‘StoryWeaver’ in dialogue

- scenes/ui_elements/dialogue/balloon.tscn
- scenes/ui_elements/dialogue/components/balloon.gd
- scenes/ui_elements/dialogue/components/theme.tres
This rebuilds the dialogue balloon scene to be tall rather than wide, anchored to the top-left corner of the viewport, and with the speaker's name pulled out to a ribbon at the top of the scroll. The dialogue-choice buttons are moved into the scroll.
Compared to the previous implementation, derived from Godot Dialogue Manager's example, I found it clearer to use PanelContainers rather than using Panel and then carefully positioning the children. The theme is updated accordingly.
Two styles of ribbon are defined for the speaker's name, BlueRibbon and YellowRibbon. Only one is used in this implementation, but the intention is that, in future, BlueRibbon will be used for the protagonist's name and YellowRibbon for the names of NPCs.
Compared to the design, the balloon is always anchored at …
> Dialogue: Redesign balloon

- scenes/menus/intro/components/intro.dialogue
The current font does not have a glyph for `’`.
> Intro: Use straight apostrophe

- scenes/menus/splash/components/splash.gd
Previously, if you pressed Escape or Space twice in quick succession on
the splash screen, switch_to_intro() would be called twice. The second
call triggers a warning when trying to disconnect a signal from the
timer a second time.
Ignore input when PLAYER_INPUT is paused (i.e. mid-transition).
> Splash: Don't handle input while PLAYER_INPUT is is_paused

- README.md
In order to make it easier to find and share the link, add it to the readme of the project.
> Add link to playable game in README.md

- scenes/game_elements/characters/npcs/talker/components/talker.gd
- scenes/game_elements/characters/player/components/player.gd
- scenes/game_elements/characters/player/components/player_interaction.gd
- scenes/game_elements/props/collectible_item/components/collectible_item.gd
- scenes/game_elements/props/eternal_loom/eternal_loom.gd
- scenes/game_elements/props/interact_area/components/interact_area.gd
- scenes/game_elements/props/lever/components/lever.gd
- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/musical_rock.gd
- scenes/ui_elements/dialogue/components/balloon.gd
Previously, the speaker name ribbon was always blue.
With this change, the ribbon is blue if the player's character is speaking, or yellow otherwise, as designed in #162.
This is a little trickier than expected because the player controls different characters in StoryQuests (e.g. Stella in *Stella and the Missing Star*) compared to in the base game & its LoreQuests (StoryWeaver). To make this work, add a `player_name` property to the `Player` class, and pass the `Player` instance through to dialogue, similar to how the `npc_name` and NPC being interacted with is passed to the dialogue. Then, in our custom dialogue balloon, look for the Player in the list of game states, and fish out its name if found.
Fixes #230
> Dialogue: Adjust ribbon colour based on who is speaking

- scenes/game_elements/characters/npcs/story_quest_starter/components/story_quest_starter.dialogue
This is functionally the same as the “No!” option and consensus during
an in-person playtest was that we should remove it.
> StoryQuestStarter: Remove “Maybe later” dialogue branch

- scenes/world_map/frays_end.tscn
Now that we are able to set decoration textures through the editor, we can add some variation to houses & trees in frays end
> Use new sprites in Frays End to give more variation

- scenes/game_elements/props/tree/components/tree.gd
Previously, the x-axis and y-axis scale were randomized independently, each to a random value in the range [0.8, 1.2]. This meant that you could get trees that were very tall but narrow, or very short but wide.
Instead, choose the y-axis scale (height) randomly from that same range, but then choose the x-axis scale to be derived from the y-axis scale, scaled within a narrower band. This means that if the y-axis scale is 0.8, then the x-axis scale is constrained to be within 0.72 and 0.88; similarly if the y-axis scale is 1.2, the x-axis scale is between 0.96 and 1.44.
> Tree: Randomize x scale proportionally to y

- .github/workflows/discord.yml
We want to highlight work that gets merged into the game in the Discord so we can celebrate learner achievements. This also provides a lower-noise feed for anyone interested in following along with Threadbare development beyond just releases.
GitHub's built-in webhooks are not granular enough for our needs; they deliver _all_ PR-related events which causes too much noise. Instead, this workflow uses a GitHub Action to deliver a notification to Discord via webhook only when a pull request is merged into main.
- Requires a `DISCORD_WEBHOOK_MERGE` repository secret
- Uses https://github.com/marketplace/actions/actions-for-discord
- Docs: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
> ci: Notify Discord of PRs merged to main via webhook

- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/bonfire.gd
- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/bonfire.tscn
- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/music_puzzle.gd
The bonfires now have an interact area. If the player interacts with it, it calls the puzzle to play the melody of the corresponding fire.
Fixes #234 
Depends on #275 to be merged
> Add interact area to bonfires to enable players to listen to its melody

- scenes/world_map/frays_end.tscn
Otherwise they turn when being involved in conversations. Regression introduced when rebuilding the Fray's End scene.
Fix https://github.com/endlessm/threadbare/issues/281
> Elders should look at the front

- scenes/quests/lore_quests/quest_001/2_ink_combat/components/ink_combat.gd
Previously you could move the player while the opening dialogue was playing.
Pause PLAYER_INPUT while the dialogue is playing.
> Ink combat: Pause player input during intro dialogue

- scenes/game_elements/props/collectible_item/components/collectible_item.gd
In 77834b0b the collectible animations were improved, and the sprite starts with a transparent modulate color to avoid a flicker effect. But the result of this is that if the collectible starts already revealed (which is the case in the stealth game), the collectible is transparent forever because the revealed animation doesn't play.
So in addition to set visibility when already revealed at the start, set modulate color to white.
> Fix collectible that starts revealed

- scenes/game_elements/props/clouds_overlay/clouds_overlay.tscn
- scenes/game_elements/props/clouds_overlay/components/clouds_overlay.gd
- scenes/game_elements/props/clouds_overlay/components/clouds_overlay.gd.uid
- scenes/game_elements/props/clouds_overlay/components/clouds_shadows.gdshader
- scenes/game_elements/props/clouds_overlay/components/clouds_shadows.gdshader.uid
- scenes/world_map/frays_end.tscn
The clouds_overlay, when added to a scene, will follow the camera around and paint cloud shadows all over it.
It can be adjusted to allow for different cloud densities, wind speeds, wind directions, opacity, and fluffyness.
https://github.com/user-attachments/assets/c0e255e6-447d-4d1c-a7f1-a9411624f840
Fixes #124
> Add cloud overlay to allow scenes to have cloud shadows

- .pre-commit-config.yaml
- project.godot
- script_templates/Node/Default.gd
Tired of getting your PR rejected because you forgot to add the licensing info in your scripts and dialogues?
Not anymore. Now, whenever you create a new dialogue, it will look like this by default:
```
~ start
Elder: [[Hi|Hello|Howdy]], StoryWeaver.
=> END
```
And if you create a new script, there will be a new template in the list you can use:
https://github.com/user-attachments/assets/15620817-e730-4bd6-bb86-f081d5fcbbac
> Add licensing to default templates

- scenes/ui_elements/dialogue/balloon.tscn
- scenes/ui_elements/dialogue/components/balloon.gd
- scenes/ui_elements/dialogue/components/theme.tres
Dialogue: Add visible “next” Button
In playtesting we have found that not all players realise that they need
to press a key to progress the dialogue.
Add a button that, when pressed, acts like the input action for "next"
(Enter, Space, Xbox joypad A) has been entered.
Style variations for the button added in a new style called FlatButton.
Fixes https://github.com/endlessm/threadbare/issues/263
> Dialogue: Add visible “next” Button

- scenes/quests/lore_quests/quest_001/2_ink_combat/components/dialogues/ink_well.dialogue
Currently this dialogue refers to InkDrinkers. But the guards in the stealth quest are using a different asset, and we do not currently have the necessary animations to replace them with InkDrinkers.
Refer to them as StoryVores in the dialogue that closes the preceding scene instead.
Fixes https://github.com/endlessm/threadbare/issues/309
> Tweak dialogue introducing stealth quest

- scenes/menus/intro/intro.tscn
- scenes/ui_elements/cinematic/cinematic.gd
- scenes/world_map/frays_end.tscn
After we redesigned this scene to have the player start outside Fray's End proper, finishing a quest has regressed: the player should be placed back near the loom in order to deposit the threads they have collected.
Add an optional spawn_point_path property to Cinematic, like the similar feature on Teleporter.
Move the player's default location to near the loom. Add a spawn point at the player's previous default location. Set the spawn_point_path property on the intro cinematic.
I did it this way rather than the other way around (keep the player's default position & place a spawn point in front of a loom) because this way we only need to set the spawn point property in one scene that we maintain, rather than requiring the property to be set correctly at the close of every quest, which to …
> Fray's End: Spawn at loom after completing a quest

- addons/dialogue_manager/plugin.gd
- addons/dialogue_manager/settings.gd
- project.godot
Up till now, adding or removing dialogue files has caused project.godot to be
updated. This has repeatedly caused conflicts even with our small team working
on the game, and would lead to chaos when learners start adding their own
dialogue and we try to merge their changes.
The game is not currently localized, and you could imagine that we might not
want to localize all learners' dialogue files, only the core game and LoreQuest
dialogue.
Using a new feature I patched into the addon (and sent upstream), disable this
behaviour, and delete the existing list from project.godot.
> Don't add dialogue to translatable files

- scenes/game_elements/characters/npcs/talker/components/talker.gd
- scenes/game_elements/characters/player/components/player.gd
- scenes/game_elements/characters/player/components/player_fighting.gd
- scenes/game_elements/characters/player/components/player_interaction.gd
- scenes/game_elements/props/eternal_loom/eternal_loom.gd
- scenes/quests/lore_quests/quest_001/2_ink_combat/components/ink_combat.gd
Previously, player input (directions, interacting, and repelling ink
blobs) was all done in the _process() method of Player, PlayerFighting
and PlayerInteraction. This meant that we had to take special steps to
avoid processing input during and at the end of dialogue.
Godot Dialogue Manager takes care to mark all input events as handled
during dialogue, and documents in its FAQ that player input should be
handled in _unhandled_input() rather than _process().
https://github.com/nathanhoad/godot_dialogue_manager/blob/main/docs/FAQ.md#how-do-i-stop-my-player-from-moving-while-dialogue-is-showing
Handle player input in _unhandled_input(). Two cases are simple:
- Player: add an input_vector field, update it from _unhandled_input(),
and use it in _process()
- PlayerFighting; rename _process() …
> Player: Handle input in _unhandled_input() not _process() 

- scenes/game_elements/props/collectible_item/collectible_item.tscn
- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/musical_rock.tscn
So the label doesn't interfere with the sprite image.
Move it above the sprite, just like the rocks in the music puzzle game.
Fix https://github.com/endlessm/threadbare/issues/338
> Collect item: Move label to the top

- scenes/ui_elements/dialogue/balloon.tscn
- scenes/ui_elements/dialogue/components/theme.tres
It has turned out that the previous button style makes it hard to tell which choice is focus when there are only 2 choices: is it the blue button with a grey border, or the dimmer yellow-brown button with a gold border?
Adjust the FlatButton style variation to show no background (actually a fully-transparent modulation of the same texture) when unfocused, and the flat sign texture when focused. Set the response buttons to use this.
Add a new FlatNextButton style, derived from FlatButton, that implements the previous FlatButton style of having a visible background even when unfocused, and set the "next >" button to use it. (This is because this button is not actually focused: the dialogue balloon itself grabs focus, for reasons I don't fully understand.)
I chose to define the styles this …
> Dialogue: Use flat buttons for response menu

- scenes/quests/lore_quests/quest_001/2_ink_combat/components/fill_game_logic.gd
- scenes/quests/lore_quests/quest_001/2_ink_combat/components/throwing_enemy/components/throwing_enemy.gd
If the is no target label to add to a projectile, simply don't throw.
Fix https://github.com/endlessm/threadbare/issues/276
> Fill game: Fix enemy throwing without target label

- scenes/game_elements/props/clouds_overlay/components/clouds_overlay.gd
- scenes/world_map/frays_end.tscn
Previously, since the cloud overlay was running in the inspector, the offset of the clouds would change every frame. That's great to see how it looks, but since that's a value that is persisted in the scene, it was causing changes in the frays_end scene file.
Now, the clouds will still move across the level as usual, but on save the offset parameter of the shader gets reset to 0 so it's always the same value and we don't commit new unwanted changes to fray's end by mistake.
> Cloud overlay resets shader's offset parameter on save

- scenes/globals/scene_switcher/scene_switcher.gd
Previously, the target scene was loaded in full before starting the fade-out transition.
Instead, start loading the scene asynchronously at this point, then start the transition. Only wait for the scene to be fully loaded at the blank point of the transition. This means the transition starts immediately, and if the scene takes longer than 1 second to load, the pause is at the blank point: a natural place for it.
Helps #368
> Load next scene asynchronously during transition

- scenes/globals/scene_switcher/transitions/transitions.tscn
Previously, the Transitions scene (a CanvasLayer with a ColorRect covering the viewport) was initially visible, although the ColorRect itself has a material that makes it fully transparent. At the start of any transition, it is explicitly made visible, then hidden at the end of the transition.
This means that on the first scene played, an invisible CanvasLayer swallows all clicks on the scene; and so if you play an individual scene, mouse input does not work until you switch to another scene. It is desirable that clicks (and other input) are blocked during a transition, but not outside one.
Set the scene's visible property to false by default.
> Transitions: Hide by default

- scenes/menus/title/components/credits.gd
- scenes/menus/title/components/credits.gd.uid
- scenes/menus/title/components/credits.tscn
- scenes/menus/title/components/main_menu.gd
- scenes/menus/title/components/main_menu.gd.uid
- scenes/menus/title/components/main_menu.tscn
- scenes/menus/title/components/title_screen.gd
- scenes/menus/title/title_screen.tscn
Factor the main menu out of the title screen, placing it into a TabContainer without visible tabs or background to use as a view switcher.
Add a credits scene, with one panel for contributors to the game itself and another for third-party components for which attribution is required. Initially the text of each is hardcoded rather than being derived from the source tree in some way.
Fixes https://github.com/endlessm/threadbare/issues/53
> Title: Add credits scene

- project.godot
- scenes/game_elements/props/background_music/background_music.tscn
- scenes/game_elements/props/background_music/components/background_music.gd
- scenes/globals/music_player/music_player.gd
- scenes/globals/music_player/music_player.gd.uid
- scenes/globals/music_player/music_player.tscn
- scenes/quests/lore_quests/quest_001/1_music_puzzle/music_puzzle.tscn
Add a new global, MusicPlayer, that holds an AudioStreamPlayer that is accessible from everywhere.
Change the code in BackgroundMusic so it uses that AudioStreamPlayer instead of an internal one. Also, change the code so it checks if the AudioStream it will play is the same as the one that is currently playing, if that's the case, do nothing.
When transitioning out of a level, the BackgroundMusic node starts a tween that mutes the global AudioStreamPlayer by tweening its volume_db to -100 (linear_to_db(0.00001)). On _ready() of the next BackgroundMusic node, the AudioStreamPlayer volume_db would tween back to 0.0. This solves 2 things:
- We have fade out and fade in between scenes.
- If a level doesn't have background music, we don't have to do anything special in that level because the …
> Make background music continue between levels

- scenes/game_elements/props/checkpoint/checkpoint.tscn
- scenes/game_elements/props/checkpoint/components/checkpoint.dialogue
- scenes/game_elements/props/checkpoint/components/checkpoint.dialogue.import
- scenes/game_elements/props/checkpoint/components/checkpoint.gd
- scenes/quests/lore_quests/quest_001/3_stealth_level/stealth_level.tscn
- scenes/quests/story_quests/template/1_stealth/stealth_template.tscn
Previously, there was no visible indication that there are checkpoints in the stealth level, or that you have reached one. In playtesting, some players suggested that we should add checkpoints to the stealth level, not realising that they were already present.
Add a sprite to the checkpoint scene. Hide it until the player enters the checkpoint area.
Add a small collision shape to it, so that the player can't walk through it. Deactivate that collision shape when the sprite is invisible.
Enable y-sorting on the parent node of all the checkpoints in the two stealth levels currently in the source tree.
For now, a scarecrow is used to indicate the checkpoint, as a placeholder. I have not added any kind of animation or sound effect when the checkpoint is reached.
You can interact with the …
> Indicate checkpoints visually

- scenes/game_elements/props/collectible_item/components/collectible_item.gd
- scenes/globals/game_state/inventory/inventory_item.gd
Previously the interaction prompt just read "Collect". Set it dynamically based on the type of thread being collected, i.e. "Collect Imagination".
> CollectibleItem: Include type in interact prompt

- project.godot
- scenes/game_elements/characters/npcs/talker/components/default.dialogue
- scenes/game_elements/props/checkpoint/components/checkpoint.dialogue
- scenes/game_elements/props/checkpoint/components/checkpoint.gd
I noticed a few places where the name "StoryWeaver" is hardcoded in dialogue that will, by default, be used in StoryQuests if certain components are used there without customisation – namely, stealth challenge checkpoints and default NPC dialogue.
Update all of these to get the player name dynamically, and make it possible to customise the checkpoint dialogue in any case.
> Parameterise player name in default dialogue

- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/music_puzzle.gd
Suppose that the sequence of notes that you have to play is C D E G, and you play C D C D E G. This should be accepted as a valid solution, because although the third note played is wrong for the 3rd note of the melody, it's the correct first note. But this regressed in commit bf96e5f.
After failing to match the note in the middle of the melody, match it again at the start.
Fixes https://github.com/endlessm/threadbare/issues/437
> Music Puzzle: On wrong note, match again at start of melody

- scenes/quests/lore_quests/quest_001/1_music_puzzle/music_puzzle.tscn
- scenes/world_map/frays_end.tscn
These look great but unfortunately they currently cause the scenes that use them to take a long time to load.
Removing them makes the scenes load essentially instantly, which makes for a better player experience and avoids us having to write a loading screen!
Remove the clouds. We can reinstate them when their loading time has been improved.
See https://github.com/endlessm/threadbare/issues/380
> Remove cloud overlays

- .pre-commit-config.yaml
Other addons can be managed by us, so we can apply the same checks as the project files to those.
> Pre commit: Only exclude the Dialogue Manager addon

- REUSE.toml
- addons/sprite_frames_exported_textures/plugin.cfg
- addons/sprite_frames_exported_textures/sprite_frames_editor_property.gd
- addons/sprite_frames_exported_textures/sprite_frames_editor_property.gd.uid
- addons/sprite_frames_exported_textures/sprite_frames_exported_textures.gd
- addons/sprite_frames_exported_textures/sprite_frames_exported_textures.gd.uid
- addons/sprite_frames_exported_textures/sprite_frames_helper.gd
- addons/sprite_frames_exported_textures/sprite_frames_helper.gd.uid
- addons/sprite_frames_exported_textures/sprite_frames_inspector_plugin.gd
- addons/sprite_frames_exported_textures/sprite_frames_inspector_plugin.gd.uid
- project.godot
There are actually 2 valid ways of creating a new spritesheet:
- Duplicating it from the editor's filesystem.
- In the inspector of a selected node that exposes a SpriteFrames, click _Make Unique_.
Then, once the new spritesheet is created, it's just either dragging a texture to the one that the user wants to swap.
https://github.com/user-attachments/assets/732af1f1-a11d-4dd1-9340-da68926a93a5
> Animated sprites with configurable textures

- scenes/menus/storybook/components/quest.gd
- scenes/menus/storybook/components/quest.gd.uid
- scenes/menus/storybook/components/storybook.gd
- scenes/menus/storybook/components/storybook.gd.uid
- scenes/menus/storybook/storybook.tscn
- scenes/quests/story_quests/template/quest.tres
This is not actually wired up to the game, because there is currently only one StoryQuest in the source tree. The intention is that, once we have more than one, interacting with the StoryQuest elder would give you this interface (or an improved version of it) to choose which one to play.
The purpose of adding this now is to define the "Quest" resource type and place it in the StoryQuest template directory.
This could also be used to populate the Credits screen (https://github.com/endlessm/threadbare/issues/402).
Fixes https://github.com/endlessm/threadbare/issues/470
> Add storybook to select a StoryQuest to play

- scenes/game_elements/characters/enemies/guard/components/guard.gd
- scenes/game_elements/characters/enemies/throwing_enemy/components/throwing_enemy.gd
- scenes/game_elements/characters/npcs/shared_components/npc.gd
- scenes/game_elements/characters/npcs/talker/components/talker.gd
- scenes/game_elements/characters/player/components/player.gd
- scenes/game_elements/props/filling_barrel/components/filling_barrel.gd
- scenes/game_elements/props/interact_area/components/interact_area.gd
- scenes/game_elements/props/projectile/components/projectile.gd
- scenes/globals/game_state/inventory/inventory_item.gd
- scenes/globals/scene_switcher/transitions/transitions.gd
- scenes/menus/storybook/components/storybook.gd
- scenes/ui_elements/cinematic/cinematic.gd
- scenes/ui_elements/story_quest_progress/components/story_quest_progress.gd
This makes the scripts immune to file renames.
It is also less readable, but the Godot editor understands these paths and you can Ctrl-click on them in the script editor to see the resource open in the Inspector. From there you can also use the top bar menu to show the file in the Filesystem dock. Or, if it is a scene, it opens in a new tab directly, then right-clicking in the root node it can be shown in the Filesystem dock.
> Switch all res:// preload references to UID paths

- scenes/game_elements/characters/player/components/animation_player.gd
Previously, if the player's AnimationPlayer was set to the blow animation and it changed mode from FIGHTING to COZY, it would stay looping in the blow animation.
Changed the code so it can never be in a fighting animation if the mode is COZY by matching by the player_mode first.
Then, changed the logic of the fighting mode so it handles the cases in which the player should walk because they are not attacking that frame.
Finally, adding a comment to explain how if the blow animation is played, it's only cut off if it is at the anticipation phase.
Fixes https://github.com/endlessm/threadbare/issues/421
> Fix attack animation getting stuck when changing modes

- scenes/game_elements/props/filling_barrel/components/filling_barrel.gd
- scenes/game_elements/props/filling_barrel/filling_barrel.tscn
Previously, an already filled barrel would still execute the fill logic if it was hit by a projectile during its completed animation. This allowed clearing an ink combat challenge without actually filling all barrels.
Now, if the filling barrel has been filled and gets hit by a projectile, it doesn't do anything.
The filling barrel collisions are also disabled, but the early return is also there just in case more than one projectile hit the filling barrel in the same frame.
Fixes https://github.com/endlessm/threadbare/issues/442
> Filling Barrel: Fix it was possible to fill it twice

- scenes/game_elements/characters/player/components/player.gd
Inspired by the same warnings for the guards.
Note: This effectively adds a warning to the player template SpriteFrames aka "egg guy" because it's missing the attack_02 animation on purpose.
> Player: Warn when SpriteFrames animations are wrong

- scenes/game_elements/props/filling_barrel/components/filling_barrel.gd
- scenes/game_elements/props/filling_barrel/components/filling_barrel_sprite_frames.tres
- scenes/game_elements/props/filling_barrel/filling_barrel.tscn
Previously, the amount of times a filling barrel needed to be filled was hardcoded to 3, and the animation for it could be configured, but it would always need to have 4 frames.
Now, that requirement was relaxed, the FillingBarrel exposes a SpriteFrames instead of a texture, and the amount of times it needs to be filled depends on the amount of frames in the SpriteFrames' animation.
> Determine needed fills from animation

- scenes/game_elements/props/decoration/hiding_mushroom/hiding_mushroom.gd
Given the different states of the mushrooms, sometimes it's difficult to know whether or not the hide or reveal animations should play.
This commit makes setting the "is_hidden" value idempotent and deletes a validation that caused an issue where the mushrooms wouldn't hide when the player was nearby.
> Fix mushrooms not hiding

- scenes/game_logic/stealth_game_logic.gd
- scenes/quests/lore_quests/quest_001/3_stealth_level/stealth_level.tscn
This was setting every guard to instant player detection to true or false since commit 67c81f46. But that prevents mixing guards with instant detection in the same scene, making the modding inflexible. With this change, the 2 guards next to the bridge in the Lore Stealth game should detect the player instantly. Thus this fixes the regression.
Fix https://github.com/endlessm/threadbare/issues/502
> Stealth logic: Remove global instant detection

- scenes/game_elements/props/eternal_loom/components/eternal_loom.gd
- scenes/game_elements/props/eternal_loom/components/eternal_loom_interaction.dialogue
- scenes/globals/game_state/game_state.gd
When the player interacts with the Eternal Loom while in possession of the threads of Memory, Imagination, and Spirit (after completing a quest) we previously played an animation of the threads entering the loom, and then some dialogue spoken by the Elders.
After the animation plays, switch scenes to a series of three Sokoban puzzles where the player repairs the loom using the threads they have collected. Once they have completed all three puzzles, return to Fray's End and play the Elder dialogue.
Fixes https://github.com/endlessm/threadbare/issues/440
> Link Sokoban puzzles to the Eternal Loom

- scenes/quests/story_quests/template/1_stealth/collected.dialogue
- scenes/quests/story_quests/template/1_stealth/stealth.tscn
Reduced the text to just give a slightly more simplified hint or breadcrumb for the learner as to where to go next. I also referred to the label is "Next Scene" instead of "Scene to Go To" because we will be adjusting that label going forward.
> simplify dialogue for learner stealth template when item is collected

- scenes/game_elements/props/checkpoint/components/checkpoint.dialogue
- scenes/quests/story_quests/template/0_intro/intro.dialogue
- scenes/quests/story_quests/template/1_stealth/checkpoint.dialogue
- scenes/quests/story_quests/template/1_stealth/checkpoint.dialogue.import
- scenes/quests/story_quests/template/1_stealth/stealth.dialogue
- scenes/quests/story_quests/template/1_stealth/stealth.tscn
- scenes/quests/story_quests/template/2_combat/combat.dialogue
- scenes/quests/story_quests/template/2_combat/combat.tscn
I reduced the amount of text and simplified the guidance within the dialogue in the intro template, checkpoint, and combat template scenes just to keep the "instruction" there to a bare minimum of bread crumbs or hints. This is to go along with a previous PR where I adjusted the language of the collectible dialogue for the stealth template scene as well.
Within the combat scene and stealth scene I also generalized the player name property to just be **Player Name** instead of Storyweaver and a made a few nodes sound more generic to encourage more open creativity/ideation for learners about the potential these components have for their unique StoryQuests. 
- Barrels are targets
- ThrowingEnemy is a ThrowingNPC
- I left "Guards" alone in stealth but will review with others on this one as …
> Simplify learner templates

- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/xylophone/musical_rock.gd
- scenes/quests/lore_quests/quest_001/1_music_puzzle/music_puzzle.tscn
- scenes/quests/story_quests/template/3_music_puzzle/music_puzzle.tscn
Previously, the colour of each MusicalRock was set in the rock's script, which set the modulate property on the sprite. The colour was chosen by picking 7 evenly-spaced hues for the 7 possible notes, and the same saturation and value for each.
This was convenient, especially since we only have one rock asset. But it makes it harder to have different appearances in different instances of the musical-rock/sequence puzzle. For example, you may want the objects to be four different shapes, not recoloured versions of the same asset.
Remove the logic that recolours the rock based on its note. Instead, modulate each rock in the scene that uses it, using the same colour that was previously generated from the note in code.
This looks a bit weird in the editor because the rock's collision shapes …
> MusicalRock: Remove automatic modulation by note

- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/bard.gd
- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/bonfire_sign/bonfire_sign.gd
- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/bonfire_sign/bonfire_sign.tscn
- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/music_puzzle.gd
- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/sequence_puzzle_step.gd
- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/sequence_puzzle_step.gd.uid
- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/xylophone/musical_rock.gd
- scenes/quests/lore_quests/quest_001/1_music_puzzle/music_puzzle.tscn
- scenes/quests/story_quests/template/3_music_puzzle/music_puzzle.dialogue
- scenes/quests/story_quests/template/3_music_puzzle/music_puzzle.tscn
Conceptually this music/sequence puzzle is a series of steps. Each step
has a sequence of nodes that the player must interact with in that
order, and a sign which provides a hint and lights up when that step is
solved. When all steps have been solved, the puzzle as a whole is
solved.
Previously, the sequences were represented as a string containing the
names of musical notes, which corresponded to a note property on
MusicalRock nodes. This makes the puzzle specific to musical melodies,
and is also error-prone: nothing prevented the level designer entering
the string "Sausages" as a "melody".
There was also a requirement that there be the same number of melodies
as bonfire signs, enforced with a warning in the editor.
Introduce a SequencePuzzleStep node, which contains the sequence for …
> Music puzzle: Represent steps as nodes

- scenes/game_elements/characters/player/components/player_fighting.gd
The issue could happen when a player switched from fighting mode to cozy mode while the got hit animation was playing.
Fixed by setting the modulate to 1 when exiting the fighting mode.
Fixes https://github.com/endlessm/threadbare/issues/497
> Fix: storyweaver becomes transparent when exiting combat

- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/bonfire_sign/bonfire_sign.gd
- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/bonfire_sign/bonfire_sign.tscn
- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/music_puzzle.gd
Commit c4bdddc changed the signs' default behaviour so that each sign can be interacted with before it is lit, allowing the player to see a demo of the corresponding melody. This is a deliberate choice to make the puzzle easier, although it was made configurable in case someone wants a harder puzzle.
However, that change introduced a problem. At the start of the puzzle, only the melody for the first sign is accepted as input, but all four signs were interactive, misleading the player.
Add an interactive_hints property to the MusicPuzzle logic node, controlling whether the sign for the current step of the puzzle should be interactive. Add code to propagate this through to the BonfireSigns. Rename the corresponding property on BonfireSign and stop exporting it – this is now a whole-puzzle …
> Music puzzle: Only allow interacting with the next sign

- scenes/game_elements/props/eternal_loom/eternal_loom.tscn
The animation for returning the collected Memory, Imagination and Spirit to the Eternal Loom was using the sprites for the HUD. Use the sprites for the world instead.
Fix https://github.com/endlessm/threadbare/issues/586
> Eternal Loom: Use world sprites for collectibles

- scenes/game_elements/characters/enemies/guard/components/guard.gd
- scenes/game_elements/characters/enemies/throwing_enemy/components/throwing_enemy.gd
- scenes/game_elements/characters/enemies/throwing_enemy/throwing_enemy.tscn
- scenes/game_elements/characters/player/components/player.gd
- scenes/game_elements/characters/player/player.tscn
- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/xylophone/musical_rock.gd
- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/xylophone/musical_rock.tscn
- scenes/quests/lore_quests/quest_001/1_music_puzzle/music_puzzle.tscn
- scenes/quests/lore_quests/quest_001/2_ink_combat/ink_combat_round_1.tscn
- scenes/quests/lore_quests/quest_001/2_ink_combat/ink_combat_round_2.tscn
- scenes/quests/lore_quests/quest_001/2_ink_combat/ink_combat_round_3.tscn
- scenes/quests/lore_quests/quest_001/3_stealth_level/stealth_level.tscn
- scenes/quests/story_quests/template/1_stealth/stealth.tscn
- scenes/quests/story_quests/template/2_combat/combat.tscn
- scenes/quests/story_quests/template/3_music_puzzle/music_puzzle.tscn
- scenes/world_map/frays_end.tscn
Fix https://github.com/endlessm/threadbare/issues/585
@wjt @jbourqueendless I wonder if we want this. The template settings (assets, etc) are the default even for Lore. And Lore "dresses" eg. the player to be the StoryWeaver.
[Grabación de pantalla desde 2025-05-14 11-25-13.webm](https://github.com/user-attachments/assets/21ded949-ddef-4bdc-a6f5-e02d69eb9f72)
I have only changed a few things to demo the concept (player name, player SpriteFrames, throwing enemy SpriteFrames). And applied them to only one Lore scene, while clearing one template scene. If we decide to do this, we better do it soon as it is a change that will affect all the project!
> Lore on top of template

- project.godot
Undo is Xbox B, which is consistent with this often meaning "back" in menus (including the menus in this game).
Reset is Xbox X, which is quite arbitrary but perhaps the mnemonic can be that "X" is destructive?
Fixes https://github.com/endlessm/threadbare/issues/488
> Add controller bindings for Sokoban undo and reset

- scenes/game_elements/props/sequence_puzzle_hint_sign/components/sequence_puzzle_hint_sign.gd
- scenes/game_elements/props/sequence_puzzle_hint_sign/sequence_puzzle_hint_sign.tscn
Previously, interacting with a hint sign would always demonstrate the sequence. Now that it is possible to supply a `hint` animation to play on the sign itself (as is done in the template), some level designers may prefer to not demonstrate the sequence and make the puzzle more than a memory/imitation game.
For example, the template puzzle has two signs. Each sign shows a different series of symbols that have a natural correspondence to a coloured object (e.g. green = leaf). You could imagine changing this puzzle so that the player learns the correspondence from the first sign (which demonstrates the sequence of objects) and then has to interpret the symbols alone on the second sign. (They can replay the first sign if they have forgotten.)
I also adjusted the interact prompt on the sign. …
> HintSign: Make demonstrating sequence optional

- scenes/globals/scene_switcher/scene_switcher.gd
Previously, when switching scenes, current_spawn_point would only be set if a non-empty spawn_point parameter was passed to change_to_*(). There is only one case in the project today which passes a non-empty path here: the transition from the intro to Fray's End. (All other uses of cinematic.gd leave spawn_point_path unset; as do all uses of teleporter.gd.) The only other place where GameState.current_spawn_point is updated is by checkpoints in stealth challenges.
spawn_point_path only has a well-defined meaning together with a particular scene, so if we are switching scene we should clear it. In particular, this fixes a bug where if you play the StoryQuest template stealth quest (which has a node named Checkpoints/Checkpoint), and then go on to play the LoreQuest stealth quest (which …
> SceneSwitcher: Unconditionally set current_spawn_point

- scenes/game_elements/props/decoration/hiding_mushroom/hiding_mushroom.gd
- scenes/game_elements/props/decoration/hiding_mushroom/hiding_mushroom.tscn
- scenes/world_map/frays_end.tscn
Previously, the behaviour of the mushroom was configurable: it could be configured to start hidden, or start visible; and it could be configured to stay hidden/revealed once its state changes. I found the logic confusing, particularly the dynamic redefinition of the "stay hidden/revealed" property based on the value of is_hidden. And the behaviour of the four instances in Fray's End was incorrect: they are supposed to start revealed, and hide when the player gets near.
Remove all configuration from the mushroom. Make it always follow the behaviour of being visible unless the player is nearby.
Fixes https://github.com/endlessm/threadbare/issues/580
> hiding_mushroom: Simplify behaviour

- scenes/menus/title/title_screen.tscn
The quiet version we were using before is mastered at a substantially lower volume than the loud version, and (more to the point) the other pieces of in-game music. This meant that an appropriate volume for the main game is too quiet for the title screen; and that if you crank up the music volume on the title screen to compensate, you are blasted by the in-game music.
> Title: Use loud version of main theme

- scenes/quests/story_quests/template/0_template_intro/template_intro_components/template_intro.dialogue
- scenes/quests/story_quests/template/1_template_stealth/template_stealth_components/template_checkpoint.dialogue
- scenes/quests/story_quests/template/1_template_stealth/template_stealth_components/template_collected.dialogue
- scenes/quests/story_quests/template/1_template_stealth/template_stealth_components/template_stealth.dialogue
- scenes/quests/story_quests/template/2_template_combat/template_combat_components/template_combat.dialogue
- scenes/quests/story_quests/template/3_template_sequence_puzzle/template_sequence_puzzle.dialogue
- scenes/quests/story_quests/template/4_template_outro/template_outro_components/template_outro.dialogue
Rename NPC to KnitWitch in template to match lore. Edit narrative text in template scenes to clarify tasks for learners.
> Rename NPC to KnitWitch in template and edit narrative text in template scenes

- scenes/game_elements/characters/player/components/player.gd
Previously, is_running() was defined solely based on whether the user is holding the "running" action (Shift or L1). However, in combination with an analogue joystick, it is possible to move the player slowly while holding L1, in which case the running animation looks weird.
Instead, define is_running() based on the player's current speed being greater than the walk speed. This means that if the player holds L1 but inclines the joystick only slightly, the normal walk animation plays and no dust particles are emitted.
> Player: Define is_running based on current speed

- scenes/game_elements/characters/enemies/throwing_enemy/components/throwing_enemy.gd
The limit is currently one second because in 3d3ef9be when switching to AnimationPlayer the animation was set to that length. It should be 0.8 seconds because that's the sum of the attack anticipation and attack animations. And probably the reason why the anticipation looks odd.
> Throwing enemy: Document current limitation in throwing_period

- scenes/menus/storybook/components/animated_texture_rect.gd
- scenes/menus/storybook/components/animated_texture_rect.gd.uid
- scenes/menus/storybook/components/quest.gd
- scenes/menus/storybook/components/storybook.gd
- scenes/menus/storybook/storybook.tscn
- scenes/quests/story_quests/template/quest.tres
For the purposes of the storybook, a quest is defined by a Quest resource with various fields that populate the storybook page.
To add some visual variety to an otherwise text-heavy page, and potentially hint that the protagonist in a StoryQuest will not be StoryWeaver, allow a quest to specify a SpriteFrames, and an animation from that SpriteFrames, which will be shown on the storybook page if present.
To do this, I had to implement a custom TextureRect that can play an animation from a SpriteFrames. This was a surprising gap in Godot's Controls to me but there are many open bugs related to this.
I also cleaned up some bits and bobs in the quest resource class and storybook scene.
Fixes #557 
https://endlessm.github.io/threadbare/branches/endlessm/quest-animation-in-storybook/#menus/story …
> Add optional animation for quest to storybook

- scenes/game_elements/characters/npcs/elder/components/elder.gd
- scenes/game_elements/characters/npcs/elder/components/lore_quest_starter.dialogue
- scenes/game_elements/characters/npcs/elder/components/story_quest_starter.dialogue
- scenes/game_elements/characters/npcs/elder/elder.tscn
- scenes/menus/storybook/components/storybook.gd
- scenes/menus/storybook/storybook.tscn
- scenes/quests/lore_quests/quest_001/quest.tres
- scenes/world_map/frays_end.tscn
Previously, each elder could trigger exactly one quest. Soon we will have more than one StoryQuest, and in due course more than one LoreQuest, so we need a way to access those.
Wire up the existing Storybook scene to the elder. Trigger its display from dialogue, hiding the dialogue balloon while the storybook is on-screen. This replaces the previous yes/no choice in each dialogue (and may address #575).
Fixes #164
----
Test it at:
https://endlessm.github.io/threadbare/branches/endlessm/add-storybook-to-storyquest-elder/#uid://cufkthb25mpxy
> Elder: Offer the player a storybook

- scenes/game_elements/characters/npcs/elder/components/elder.gd
In commit 1edfb44e78faab2a08621f467e9e442ccd2df978, I moved talker.gd's connection to DialogueManager.dialogue_ended to
_on_interaction_started(). What I missed is that elder.gd overrides this function without chaining up. So the elders' _on_dialogue_ended() is never called, making it impossible to enter a quest.
Copy the same new code into elder.gd.
> Elder: Fix end of dialogue

- scenes/game_elements/props/sequence_puzzle_object/sequence_puzzle_object.tscn
- scenes/quests/lore_quests/quest_001/1_music_puzzle/components/dialogues/musician.dialogue
- scenes/quests/story_quests/template/3_template_sequence_puzzle/template_sequence_puzzle.dialogue
This is a change from @hydrolet in https://github.com/StellaQuest/threadbare/pull/31. It's OK to kick a rock, but not a tortoise. By using a more neutral term for the default interact verb, we reduce the number of cases where someone will have to figure out how to override it.
I updated the dialogue accordingly. Unfortunately "kick" is in the API and we can't change that.
> Change "kick" to "tap" in sequence puzzles

- scenes/menus/storybook/components/storybook.gd
- scenes/menus/storybook/components/storybook_page.gd
- scenes/menus/storybook/components/storybook_page.gd.uid
- scenes/menus/storybook/components/storybook_page.tscn
- scenes/menus/storybook/components/template_quest.tres
- scenes/menus/storybook/storybook.tscn
This splits some hardcoded override data for the template storyquest into a resource file, and factors out the section of the scene that displays a quest to a separate scene.
(I was experimenting with switching to a one-quest-per-page model.)
> Refactor storybook.gd somewhat

- scenes/globals/pause/pause_overlay.gd
- scenes/globals/pause/pause_overlay.tscn
And move the Resume button to the top, as it is the default focused option.
Currently this is a way to abandon and lose all your progress, because nothing is persisted. But is also a way to restart the experience if you get stuck in the Sokobans, for example.
In the future, the progress should be persisted, and the title screen should be able to offer a Resume + Restart options instead of Start, if there is progress.
Fixes https://github.com/endlessm/threadbare/issues/432
> Pause overlay: Add button to go back to title screen

- scenes/game_elements/characters/enemies/throwing_enemy/throwing_enemy.tscn
- scenes/game_elements/characters/npcs/npc_prop/fray_idle.tscn
- scenes/game_elements/props/sequence_puzzle_object/sequence_puzzle_object.tscn
The PR https://github.com/endlessm/threadbare/pull/705/ was merged accidentally. It has intentional changes in quests/story_quests/stella, but also unintentional changes in scenes/game_elements/ . So revert the unintentional changes.
> Game elements: Revert because of accidental merge

- scenes/game_elements/characters/player/player.tscn
Previously, that audio stream player had its bus set to Master, meaning it could still be heard even if the SFX volume was turned down.
Fixes https://github.com/endlessm/threadbare/issues/709
> Player: move walk sound to sfx bus

- scenes/globals/settings/settings.gd
- scenes/menus/options/components/video_settings.gd
- scenes/menus/options/components/video_settings.gd.uid
- scenes/menus/options/components/video_settings.tscn
- scenes/menus/options/options.tscn
- scenes/ui_elements/dialogue/components/theme.tres
This adds a fullscreen ON/OFF checkbox to the Options menu, that nobody asked but I wanted to implement for a while:
Like the volume settings, the change is persisted.
Note: I did not want to deal with the theme for now, there is https://github.com/endlessm/threadbare/issues/381 for that.
Note 2: Ideally all settings should be in a single GridContainer, so the labels and controls are aligned. I tried but I wasn't able to make the "Sound Settings" and "Video Settings" labels occupy 2 columns of the grid.
> Fullscreen option

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/pull_request_template.md
Adds a `bug` issue template as well as links to the playtesting feedback discussions, Q&A discussions, and Discord.
Adds a PR template to encourage double-checking the base repo/branch.
Fixes #765
> Add initial PR and issue templates

- scenes/world_map/frays_end.tscn
This is the result of loading frays_end.tscn and saving it without making any changes.
I don't know why these had the redundant type & script information when they are instanced scenes.
> Fray's End: Simplify serialised flowers in scene

- REUSE.toml
Previously, there were two rules for the pattern scenes/**/*.aseprite, one applying MPL-2.0 and the other applying CC-BY-SA-4.0.
The latter is correct. The former rule is in a block that is meant to cover machine-edited Godot resource files.
> REUSE: Fix duplicate annotation for aseprite files in scenes/

- scenes/game_elements/props/tree/components/tree.gd
When a tree is instantiated, its scale is randomised. The objective here is to introduce some variation in a forest, without requiring significant manual effort; while still allowing the level designer to choose their own scale if they really want to.
The exact way this works always surprises me when I think about it. When you place a tree into a scene:
1. In `_notification(NOTIFICATION_SCENE_INSTANTIATED)`, the tree sets its own `scale` property to a random value. Call this value `S`. At this point the tree instance is not in the tree and is not ready.
2. Now the tree is added to the scene and becomes ready. Later on you save the enclosing scene; in that scene file, the tree instance has its `scale` property set to `S`.
Next time you load that scene (at runtime or in the editor):
1. The …
> tree: Don't randomise scale when editing tree scene itself

- scenes/game_elements/characters/enemies/guard/components/guard.gd
- scenes/game_logic/stealth_game_logic.gd
The collision methods like body entered return a Node2D. But we must check that the player is the one being returned because the stealth game logic treats the node as a player, changing the mode to Player.Mode.DEFEATED when detected by the guards.
> Guard: Use correct class for Player

- scenes/game_elements/props/area_filler/area_filler.gd
Previously the maximum separation was 128px. I found this to be not sparse enough to scatter trees across an otherwise open field.
Increase the upper bound on the exported range to 256px, and add the or_more annotation so that a larger value can be typed into the field.
> AreaFiller: Allow larger separation

- scenes/game_elements/props/collectible_item/collectible_item.tscn
I noticed this while experimenting on #887 – currently CollectibleItems float above the player and you can walk through them. I think this looks bad.
[Screencast from 2025-07-03 20-13-16.webm](https://github.com/user-attachments/assets/61ecfd6f-92e6-4079-824c-7c0477108e24)
Fixed in https://endlessm.github.io/threadbare/branches/endlessm/collectible-item-collision-z_index/#quests/lore_quests/quest_001/1_music_puzzle/music_puzzle
> CollectibleItem: Fix collision & stacking

- .gitattributes
These are video files in an Ogg container.
There are currently no such videos in the tree, but we have just
received a pull request adding one. Video files should certainly be
tracked in Git LFS.
> Track *.ogv files in Git LFS

- scenes/game_elements/props/tree/components/tree.gdshader
On entry to `fragment()`, `COLOR = modulation * texture(TEXTURE, UV)`,
roughly. But the tree shader re-samples `TEXTURE` in `fragment()`,
overwriting `COLOR`. This means that the modulation is lost. In particular
this means you can't make a semi-transparent tree with the modulate
alpha channel.
In vertex(), `COLOR` is just the modulation. Save this in a varying, and
reapply it in `fragment()`.
> Support modulating trees

- export_presets.cfg
The image URL corresponds to the repository image for https://github.com/endlessm/threadbare. It will need to be manually updated when that image changes (perhaps by storing the image in the repo and adding a CI check that the export file is updated if the image has changed since the referenced commit) but this will do for now.
Fixes https://github.com/endlessm/threadbare/issues/944
> HTML export: Add social card metadata

- scenes/game_elements/characters/npcs/elder/components/elder.gd
- scenes/game_elements/characters/npcs/elder/elder.tscn
- scenes/game_elements/characters/npcs/shared_components/npc.gd
- scenes/game_elements/characters/npcs/talker/components/talker.gd
- scenes/game_elements/characters/npcs/talker/talker.tscn
- scenes/game_elements/props/checkpoint/checkpoint.tscn
- scenes/game_elements/props/checkpoint/components/checkpoint.gd
- scenes/game_elements/props/eternal_loom/components/eternal_loom.gd
- scenes/game_elements/props/eternal_loom/eternal_loom.tscn
- scenes/game_logic/talk_behavior.gd
- scenes/game_logic/talk_behavior.gd.uid
- scenes/world_map/frays_end.tscn
This node wraps few logic, but it is a reusable component that lets developers easily trigger dialogues when the player interacts with an area, with only setup and no scripting. Hopefully it will help learners create their own talkers.
Fixes https://github.com/endlessm/threadbare/issues/950
> Add Talk Behavior node

- project.godot
Revert commit 6a53c4aae . This is not a pixel-perfect or low-resolution pixel art game. So it is better if pixels aren't constrained for smoother movement.
Resolves https://github.com/endlessm/threadbare/issues/989
> Project: Remove snap transforms to pixel

- project.godot
The 16:9 display aspect ratio is the most common in PC desktop. But there are others, and notably the Steam Deck has a 16:10 display.
The game was letterboxed with black bars at the sides in displays with different aspect ratio when the aspect ratio wasn't exactly 16:9.
Now setting the window stretch mode to expand, the black areas are removed, filled with content. And the Control overlays on top of the world can occupy that empty space. For instance, the HUD at the top-right corner.
Note that in windowed mode the window can be resized to any aspect ratio, and the levels will look odd in ultrawide or ultratall cases.
Helps https://github.com/endlessm/threadbare/issues/638
> Project: Expand aspect ratio

- scenes/menus/splash/components/logo_stitcher.gd
- scenes/menus/splash/components/splash.gd
- scenes/menus/splash/splash.tscn
Since commit 73b1ba691d540e95e2c749aaf5b30bdd8f9b6d12 ("Project: Expand aspect ratio") the viewport may be wider or taller than 1920×1080. But the logo was being drawn to a plain Node2D, using points that assumed a 1920×1080 viewport. Similarly the background was a Sprite2D.
Rebuild this scene to use a Control node at the root. Change the background to a TextureRect, configured to Keep Aspect Covered.
Make the LogoStitcher node a Control rather than a Node2D, with a custom minimum size of 1920×1080 (the resolution the points in the Path2D assume) and reparent it to be centred in an AspectRatioContainer.
This keeps the logo centred in the viewport when the viewport is not at 16:9 aspect ratio.
(If we later change the base resolution of the game we will likely want to revisit this.)
Fixes …
> splash: Keep centred in viewport

- scenes/globals/settings/settings.gd
Since commit 73b1ba69, the game has been allowed to expand to fill the viewport if its aspect ratio is not 16:9 (the ratio of the base resolution). This has the downside that you can now see beyond the intended bounds of some scenes.
The problem is much more pronounced if the window is resized to very extreme aspect ratios. We can limit this by setting the minimum window size to the smallest resolution we want to support. Currently this is smaller than the base resolution of the game, so that the game is playable on screens smaller than 1920×1080, but as noted in a comment if we reduce the base resolution to the lowest resolution we support, we should probably set the minimum size to the base resolution instead.
This code is placed in the Settings global not because it is a setting, but …
> Set minimum window size to 1280×720 (720p)

- assets/first_party/logo/threadbare-logo.png.license
- docs/CONTRIBUTING.md
This codifies what I added in commit
a4e08eb42cfb8dc7bebe66740574320e802eae58, along with a tweak to specify the human who used the AI tool in the `.license` file.
> CONTRIBUTING: Document how to cite AI-generated images

- .github/workflows/export.yml
- linux/launcher.desktop
- linux/metainfo.xml
- org.endlessaccess.threadbare.yml
Our organisation has been renamed!
https://endlessaccess.org/ redirects to
https://access.endlessstudios.com/ so another option was com.endlessstudios.access.threadbare, but that's much uglier, and our email addresses will be @endlessaccess.org, so let's use that one.
Update the manifest, metainfo, desktop file and CI pipeline accordingly.
Fixes https://github.com/endlessm/threadbare/issues/1062
> Update Flatpak app ID to org.endlessaccess.threadbare

- project.godot
Commit b99c0e81f87434e6c3b5a13020c76f16c4b9fadf added config/tags to this file; whenever I save the project, Godot reorders the file.
Reorder it to be the way that it is saved.
> Reorder fields of project.godot

- .mailmap
We have changed the canonical domain name for our organisation.
It is not possible to edit the Author: and Committer: fields of old
commits, but it is possible to remap them in the output of git commands
to the new domain. Update all Endless Access team members who have
committed to date, including some of their other email addresses.
---
I also added a line to canonicalise Tobías Romero to a single email address.
---
This change is purely cosmetic. The desired result is that the following command shows a single, up-to-date email address for each user (where possible):
```console
$ git shortlog -se
1  Andrea Victoria Pavón <andrea@endlessaccess.org>
22  Cassidy James Blaede <cassidy@endlessaccess.org>
2  Dan Nicholson <dbn@endlessaccess.org>
45  Heather Drolet <heather@endlessaccess.org> …
```
> mailmap: Map @endlessos.org committers to @endlessaccess.org

- .gitignore
I found one of these for a .png file I had edited. I don't recall which app created it.
> Ignore temporary files ending with ~

- .github/workflows/github-pages.yml
This version posts a comment to the corresponding PR for each branch with a link to the playable build. It requires a new permission.
https://github.com/endlessm/amalgamate-pages/releases/tag/v2.0 https://github.com/endlessm/amalgamate-pages/issues/18
> ci: Update amalgamate-pages to v2

- scenes/eternal_loom_sokoban/components/player/sokoban_player.tscn
- scenes/eternal_loom_sokoban/components/system/board/piece_2d.gd
The spriteAnimator2D was referenced and worked with its flip_h method.
Fixes #904
> Flip player horizontally when moving left in Sokoban

- REUSE.toml
We don't currently have any MP3s, but the Hu- -sh sound effect recorded by Stephen in https://github.com/endlessm/threadbare/issues/671 is in MP3 format.
Even if we later convert this to WAV or Ogg to standardise, we can still handle it correctly.
> REUSE: Treat MP3s in assets/first_party as first-party

- scenes/globals/settings/settings.gd
Lookup the base resolution of the game from the Project Settings.
Resolves https://github.com/endlessm/threadbare/issues/1139
> Settings global: Use base resolution for minimum window size

- scenes/menus/title/components/main_menu.tscn
The main menu had some hardcoded dimensions for the previous base resolution, 1920×1080, which meant that it did not fit 1280×720:
- The logo had a custom minimum width of 1200px, and a 128px margin to its left; 1328px > 1280px.
- The button box had 128px margins to its left and right.
Remove these. To my eye the result is OK, though it will look better with a smaller button font.
Fixes https://github.com/endlessm/threadbare/issues/1138
> Main Menu: Fit 720p resolution

- scenes/game_elements/characters/components/gym_area_test.tscn
- scenes/game_logic/bounce_walk_behavior.gd
- scenes/game_logic/bounce_walk_behavior.gd.uid
- scenes/game_logic/character_sprite_behavior.gd
- scenes/game_logic/character_sprite_behavior.gd.uid
- scenes/game_logic/erratic_walk_behavior.gd
- scenes/game_logic/erratic_walk_behavior.gd.uid
- scenes/game_logic/follow_walk_behavior.gd
- scenes/game_logic/follow_walk_behavior.gd.uid
- scenes/game_logic/input_walk_behavior.gd
- scenes/game_logic/input_walk_behavior.gd.uid
- scenes/game_logic/path_walk_behavior.gd
- scenes/game_logic/path_walk_behavior.gd.uid
This is the result of the exploration in https://github.com/endlessm/threadbare/pull/777 for discussion https://github.com/endlessm/threadbare/discussions/774 .
These nodes are pure logic, intended to provide an easy way of creating
characters that move around the world with pure setup and no scripting. A more
advanced use is to have a script that can switch between these simple behaviors
to create more complex behaviors.
They are:
- BounceWalkBehavior: Make the character move and bounce on walls.
- ErraticWalkBehavior: Make the character walk around erratically.
- FollowWalkBehavior: Make the character follow a target.
- PathWalkBehavior: Make the character walk along a path.
- InputWalkBehavior: Control the character with input actions to walk and run.
They only take care of controlling …
> Add character walk behaviors

- scenes/game_logic/sequence_puzzle.gd
- Emit step_solved(step_index) when individual puzzle steps are completed
- Allows level designers to trigger custom events for each step
- Maintains existing functionality with solved signal for complete puzzle
- Fixes #783
> Add step_solved signal to SequencePuzzle

- scenes/game_elements/fx/shaker/components/shaker.gd
Add validations to avoid crashing the game through a freed instance error (a Camera2D instance called 'target').
Fix https://github.com/endlessm/threadbare/issues/934
> Shake component: Consider that the target object could be freed

- scenes/game_elements/characters/components/gym_area_test.tscn
- scenes/game_logic/walk_behaviors/navigation_follow_walk_behavior.gd
- scenes/game_logic/walk_behaviors/navigation_follow_walk_behavior.gd.uid
- scenes/quests/lore_quests/quest_002/1_void_runner/components/void_spreading_enemy.gd
- scenes/quests/lore_quests/quest_002/1_void_runner/components/void_spreading_enemy.tscn
Previously, void_spreading_enemy.gd contained movement logic somewhat
entwined with the other logic for this entity. But the movement logic
was relatively generic – follow a target using a NavigationAgent2D – and
you could imagine a different flavour of this entity that moves in a
different way, perhaps following a path.
Create NavigationFollowWalkBehavior based on the logic in
void_spreading_enemy.gd, with similar functionality to
FollowWalkBehavior but using a NavigationAgent2D rather than
straight-line pathfinding.
As with the previous implementation, if the distance to the target is
above a configurable threshold, the character runs; otherwise, they
walk. Like InputWalkBehavior, a running_changed signal is emitted, which
can be connected to CharacterSpriteBehavior to control …
> Factor NavigationFollowWalkBehavior out of void_spreading_enemy.gd

- scenes/game_elements/props/area_filler/area_filler.gd
- scenes/game_elements/props/area_filler/components/area_filler_test.tscn
It has often annoyed me that the "Refill" action cannot be undone with Ctrl-Z.
Integrate with EditorUndoRedoManager to make this possible.
In addition, change how the child nodes are instantiated so they are persisted to the scene in just the same way as if they were instantiated by hand, fixing an issue where loading and saving the scene later, without changes, would change the `.tscn`.
> AreaFiller: Support undo/redo

- scenes/eternal_loom_sokoban/components/hud/sokoban_hud.tscn
The “Z” key indicator in the Sokoban input hints HUD had its mouse cursor shape
set to CURSOR_POINTING_HAND:
> Pointing hand cursor. Usually used to indicate the pointer is over a link or
> other interactable item.
But this icon isn't interactable.
This has been set this way since commit a52f9b03e3f5066d356c63bcc56d4f47899e72d0
when the Sokoban input hints were added. I'm sure this was not intentional.
Unset it.
> Sokoban HUD: Don't override mouse cursor shape

- .github/ISSUE_TEMPLATE/bug.yml
Super minor nit, but I noticed the top form description breaking from the newline:
> <img width="777" height="507" alt="image" src="https://github.com/user-attachments/assets/1eae904c-ed7f-4490-9ba1-7c0ba7ed8bea" />
We don't need the literal line breaks in the Markdown string, so replace the literal string `|` with a folded string `>`.
> Issue template: prevent unwanted breaks in descriptions

- scenes/game_elements/props/eternal_loom/components/eternal_loom.gd
- scenes/globals/game_state/game_state.gd
Add a new field to the game state which holds an array of the paths of completed quests. Update it when the player takes threads to the loom. Clear it when the state is cleared.
Resolves https://github.com/endlessm/threadbare/issues/771
---
I tested in a new scene simulating the collection and delivery of the objects. I deleted that and didn't add it to the changes because it was to save time during testing.
https://docs.google.com/document/d/1wQst5g8896AjaVjZsPAC9E2uumBQm0mpBo9vJWxlDOA/edit?tab=t.0
> Record which quests have been played to completion

- scenes/globals/game_state/game_state.gd
If there is a game state file to restore, but it does not contain the
completed_quests key, restoring the state would crash with:
> Trying to assign an array of type "Array" to a variable of type
> "Array[String]".
This is because the `completed_quests` variable is defined thus:
var completed_quests: Array[String] = []
But it was initialised with this statement:
completed_quests = _state.get_value(GLOBAL_SECTION, COMPLETED_QUESTS_KEY, [])
And the default value given in the third argument has type Array, not
Array[String].
There are two ways to construct an empty Array[String]:
1. Cast an empty array: `[] as Array[String]`
2. Explicitly create it with that type: `Array([], String, &"", null)`
(all four parameters are required)
The first is shorter & clearer.
> Game state: Fix type error if completed_quests is not defined

- scenes/menus/title/components/main_menu.gd
Previously, choosing “Exit Game” on the main menu abruptly terminated the game.
Instead, play the normal fade-out transition, which also fades out the music,
then quit.
> Fade out when quitting

- scenes/game_elements/characters/player/components/player_hook.gd
- scenes/game_elements/props/hookable_area/components/hookable_area.gd
And use the area's global_position in its place, when not set.
Resolve https://github.com/endlessm/threadbare/issues/1246
> Hookable area: Make anchor_point optional

- scenes/game_elements/characters/components/gym_area_test.tscn
- scenes/game_logic/base_character_behavior.gd
- scenes/game_logic/walk_behaviors/bounce_walk_behavior.gd
- scenes/game_logic/walk_behaviors/erratic_walk_behavior.gd
- scenes/game_logic/walk_behaviors/follow_walk_behavior.gd
- scenes/game_logic/walk_behaviors/input_walk_behavior.gd
- scenes/game_logic/walk_behaviors/navigation_follow_walk_behavior.gd
- scenes/game_logic/walk_behaviors/path_walk_behavior.gd
And also factor out disabling physics process of these behaviors in the editor.
Helps https://github.com/endlessm/threadbare/issues/1224
> Walk behaviors: Warn if character motion mode is grounded

- scenes/globals/scene_switcher/transitions/transitions.gd
I missed this in commit fc46480dd3da3a13d0483c1f52e146f00838b685.
> Transitions: Add missing function return type

- scenes/menus/storybook/components/storybook_page.tscn
The panel texture made the text inside (description and list of authors) hard to read.
Also give the ScrollContainer the minimum width that the panel texture had (360px) so it makes use of the available space.
Before:
After:
> Storybook: Remove panel from description

- .pre-commit-config.yaml
- docs/CONTRIBUTING.md
My upstream pull request was merged:
- https://github.com/pre-commit/identify/pull/541
The maintainer chose to edit my contribution to not add the `image` tag
to piskel files:
> the `image` tag was an idea that didn't really pan out so I'm just
> going to remove it here
Of course that's their prerogative as maintainer!
Unfortunately this means that my plan from commit
e92fd6d85a60328d0767550d0149bcdee84eb858, to exclude all image files
with `exclude_types: [image]`, is not going to work. Instead we have to
add the `piskel` type explicitly to the list, and also any further
text-based image file formats that we find in future.
Add `piskel` to the exclude list. Replace the `image` type with `svg`:
`svg` is the only format with that type, and since that tag will not be
applied to any new …
> pre-commit: Recognise piskel files via exclude_types

- project.godot
This was accidentally disabled in commit
783701b70678719f77ae2b15415a459a5b06ceb6, probably by me when I resolved
merge conflicts in this file.
> Re-enable threadbare_project_settings plugin

- scenes/game_elements/characters/player/components/player_hook.gd
- scenes/game_elements/props/door/components/door.gd
- scenes/game_elements/props/hookable_area/components/hookable_area.gd
- scenes/game_elements/props/interact_area/components/interact_area.gd
- scenes/game_elements/props/projectile/components/projectile.gd
- scenes/globals/enums.gd
- scenes/quests/story_quests/shjourney/8_shjourney_outro/puerta.gd
So collision layers can referenced by a constant name rather than by an integer number. And they are all defined in a single place.
Also use "not" boolean operator instead of deprecated "!" in door.gd.
> Add global enum for collision layers

- .github/workflows/export.yml
This reverts commit c7729008360616bab0d1f5bfd20c08a7744e5709.
The problem with skipping the entire workflow is that the “Build for
web” job is a required status check to be able to merge a pull request.
I tried using dorny/paths-filter to move the “what changed?” check into
a job, so that the workflow would look like this:
check-changes
↓    |
build  |
↓    ↓
flatpak
↓
release
with the following conditions on each:
- build: run if check-changes detected non-documentation changes, or if
this is a release, or if the workflow was manually triggered
- flatpak: run if check-changes detected flatpak changes, or if this is
a release, or if the workflow was manually triggered with the checkbox
checked
- release: run only if this is a release
At this point the conditions were getting a bit …
> Revert "ci: Don't build branches/PRs that don't affect game"
