scenes/ink_combat/player/player.gd, scenes/player/player.gd, scenes/scene_switcher/scene_switcher.gd
Here I'm fixing 2 warnings and improving the way the camera is obtained for teleporting.
=> Fix warnings

project.godot, scenes/intro/intro.gd, scenes/main.tscn, scenes/stealth_level/stealth_level.tscn, scenes/stealth_level/stealth_level_challenge_complete.dialogue, scenes/world_map/song_sanctuaries.tscn, scenes/world_map/story_quest_starter.dialogue, scenes/world_map/story_quest_starter.dialogue.import, scenes/world_map/story_quest_starter.gd, scenes/world_map/story_quest_starter.gd.uid
https://endlessm.github.io/threadbare/branches/endlessm/stitch-scenes-into-playable-game/
(Go to Song Sanctuary and talk to the new NPC there.)
Fixes #32
=> Assemble playable game from disparate scenes

scenes/ink_combat/ink_combat.gd, scenes/ink_combat/ink_combat.gd.uid, scenes/ink_combat/ink_combat.tscn, scenes/ink_combat/inkwell/inkwell.gd, scenes/ink_combat/reward.gd, scenes/ink_combat/reward.gd.uid, scenes/ink_combat/reward.tscn, scenes/main.tscn
Fix https://github.com/endlessm/threadbare/issues/90
=> Stitch combat

docs/CONTRIBUTING.md
This provides guidelines to prospective contributors on topics like language (US English), coding style, Git usage, and licensing.
=> Add CONTRIBUTING file

scenes/enemies/guard/guard.gd, scenes/stealth_level/stealth_level.tscn
=> FIX #81 - Reset guards velocity on save

scenes/props/checkpoint/checkpoint.gd, scenes/props/checkpoint/checkpoint.gd.uid, scenes/props/checkpoint/checkpoint.tscn, scenes/stealth_level/stealth_level.tscn, scenes/world_map/spawn_point.gd
Fixes #37 
- Added checkpoints that can be dragged into any scene.
- Also, added some to the stealth level.
https://github.com/user-attachments/assets/f95f659d-47a8-418b-9c18-a333c95b36a0
https://github.com/user-attachments/assets/fcc7c4d3-c499-497f-9f22-dcdf2a2f5685
=> Add checkpoints

scenes/ink_combat/ink_blob/ink_blob.gd, scenes/npcs/talker/talker.gd, scenes/player/player.gd
It's really annoying that these are only shown at runtime but when I looked into it, it was hard to get them in CI: we would have to spawn the editor in LSP mode then run a custom tool that feeds each file into the LSP and logs any diagnostics it returns. Surprisingly there is no such off-the-shelf tool.
=> Fix script warnings

project.godot, scenes/ink_combat/ink_combat.gd, scenes/ink_combat/ink_combat.tscn, scenes/ink_combat/ink_drinker/ink_drinker.gd, scenes/ink_combat/intro.dialogue, scenes/ink_combat/intro.dialogue.import, scenes/ink_combat/win.dialogue, scenes/ink_combat/win.dialogue.import, scenes/props/collectible_item.gd
Helps https://github.com/endlessm/threadbare/issues/6
=> Ink combat narrative

scenes/globals/game_state/inventory/inventory_item.gd, scenes/ui_elements/story_quest_progress/components/story_quest_progress.gd
Fixes a couple of warnings seen at runtime.
One day I will snap and set something up to feed all source files through the Godot LSP in CI...
=> Add missing static types

scenes/quests/lore_quests/quest_001/2_ink_combat/components/ink_drinker/components/ink_drinker.gd
W 0:00:00:802   Variable "current_angle" has no static type.
<GDScript Error>UNTYPED_DECLARATION
<GDScript Source>ink_drinker.gd:133
=> InkDrinker: Fix UNTYPED_DECLARATION warnings

scenes/game_elements/characters/enemies/guard/components/guard.gd
Fixes #228 
-------
[Modify guard's helper button to say Add/Edit instead of just Edit](https://github.com/endlessm/threadbare/pull/250/commits/a44dcbe6994502ae464705419358af3831d64c3c) and [Guard: modify creation of new patrol path to ensure it has 2 points](https://github.com/endlessm/threadbare/pull/250/commits/62e6467462f3939c5a43cfaabe949213838098d2) can be seen here:
https://github.com/user-attachments/assets/5fb46767-da74-4fb6-9aea-a28894e09d68
----------
This feature wasn't mentioned in #228 , but I thought it could be a cool improvement to add as well:
[Guard: highlight patrol path when a guard is selected in the editor](https://github.com/endlessm/threadbare/pull/250/commits/72e68985a6e3138268c11231acc0828e46facf44)
https://github.com/user-attachments/assets/7d0c4f05-4513-4426-9c …
=> Guards improve learner side

scenes/quests/lore_quests/quest_001/2_ink_combat/ink_combat_round_1.tscn, scenes/quests/lore_quests/quest_001/2_ink_combat/ink_combat_round_2.tscn
These collectibles are never revealed, so we can safely remove them.
=> Remove collectible from combat rounds 1 and 2

scenes/game_elements/characters/npcs/story_quest_starter/components/story_quest_starter.dialogue
Adjust the ending to inform the player that they will become a different character
=> edit storyquest starter dialogue

scenes/quests/lore_quests/quest_001/2_ink_combat/components/filling_barrel/components/filling_barrel.gd, scenes/quests/lore_quests/quest_001/2_ink_combat/components/filling_barrel/components/inkwell-fill.png, scenes/quests/lore_quests/quest_001/2_ink_combat/components/filling_barrel/filling_barrel.tscn
Fix https://github.com/endlessm/threadbare/issues/292
=> Replace inkwell labels

scenes/game_elements/characters/npcs/talker/components/talker.gd, scenes/game_elements/characters/npcs/talker/talker.tscn, scenes/game_elements/characters/player/components/player_interaction.gd, scenes/game_elements/props/eternal_loom/eternal_loom.tscn, scenes/game_elements/props/fixed_size_label/fixed_size_label.tscn, scenes/game_elements/props/interact_area/components/interact_area.gd, scenes/ui_elements/shared_components/theme.tres
Fixes #167 
https://github.com/user-attachments/assets/e4459f4b-52c2-4c8d-acca-57532ce3b8d2
https://github.com/user-attachments/assets/18083052-7ea0-4704-8c2a-d39a0910a51c
=> Interact label over target

scenes/game_elements/characters/npcs/story_quest_starter/components/lore_quest_starter.dialogue.import, scenes/game_elements/characters/npcs/story_quest_starter/components/story_quest_starter.dialogue.import, scenes/game_elements/characters/npcs/talker/components/default.dialogue.import, scenes/game_elements/props/eternal_loom/eternal_loom_interaction.dialogue.import, scenes/menus/intro/components/intro.dialogue.import, scenes/quests/lore_quests/quest_001/1_music_puzzle/components/dialogues/musician.dialogue.import, scenes/quests/lore_quests/quest_001/2_ink_combat/components/dialogues/ink_well.dialogue.import, scenes/quests/lore_quests/quest_001/4_closing_transition/components/story_quest_closing_transition.dialogue.import, scenes/quests/story_quests/template/0_intro/intro.dialogue.import, scenes/quests/story_quests/template/1_stealth/stealth.dialogue.import, scenes/quests/story_quests/template/4_outro/outro.dialogue.import, scenes/world_map/components/tutorial_npc.dialogue.import
I think this was caused by uploading dialogue manager's version https://github.com/endlessm/threadbare/pull/327
=> Upload dialogue import files that were automatically updated

scenes/game_elements/props/hint/hint.gd, scenes/quests/lore_quests/quest_001/3_stealth_level/stealth_level.tscn, scenes/ui_elements/shared_components/theme.tres, scenes/world_map/frays_end.tscn
Fixes #270 
https://github.com/user-attachments/assets/66b3dd3a-0e11-43f7-b54a-c667ebd18e0c
=> Add hints to stealth level

scenes/quests/story_quests/template/4_outro/outro.tscn
Update the character in the outro scene to be the template sprite, so that learners can eventually replace with their own.
=> set outro character to template sprite

project.godot, scenes/quests/lore_quests/quest_001/2_ink_combat/components/fill_game_logic.gd, scenes/quests/lore_quests/quest_001/2_ink_combat/components/projectile/components/projectile.gd, scenes/quests/lore_quests/quest_001/2_ink_combat/components/projectile/projectile.tscn
Fix https://github.com/endlessm/threadbare/issues/355
(I just created the issue, but there were comments on this before).
=> Fill game: Remove projectiles when goal is reached

scenes/globals/game_state/game_state.gd, scenes/ui_elements/hud/components/hud.gd, scenes/ui_elements/hud/components/hud.gd.uid, scenes/ui_elements/hud/hud.tscn, scenes/world_map/components/frays_end.gd, scenes/world_map/components/frays_end.gd.uid, scenes/world_map/frays_end.tscn
=> Add hud to frays end

scenes/game_elements/characters/enemies/guard/components/guard.gd, scenes/game_elements/characters/enemies/guard/components/guard_sprite_frames.tres, scenes/game_elements/characters/enemies/guard/guard.tscn
Fixes #341 
https://github.com/user-attachments/assets/876545e8-bb90-4063-a5cc-ef75246a93f2
=> Allow configuring Guards' spritesheets in the inspector

scenes/menus/intro/intro.tscn
This has no effect, it's just something that the editor wants to do each time I save this scene.
=> intro: Reorder serialised animations

.mailmap
https://github.com/endlessm/threadbare/pull/382#issuecomment-2839924335
=> mailmap: Canonicalise JuanFdS

.editorconfig, .github/workflows/export.yml, .github/workflows/flatpak.yml, .gitignore, docs/screenshot.png, docs/screenshot.png.license, export_presets.cfg, linux/launcher.desktop, linux/metainfo.xml, org.endlessos.threadbare.yml
Adds the necessary requirements to build a Flatpak in CI or locally, and adds Flatpak builds to CI.
Of note:
- assumes an `org.endlessos.threadbare` app ID; this can be changed before release
- when a release is made, CI will attach the exported PCK file; this is helpful to semi-automate Flathub releases
Fixes #367
=> Set up Flatpak builds

scenes/game_elements/characters/player/components/player_fighting.gd, scenes/quests/lore_quests/quest_001/2_ink_combat/components/projectile/components/projectile.gd
Fix https://github.com/endlessm/threadbare/issues/337
Fix https://github.com/endlessm/threadbare/issues/331
Among other things. Like the life-extending issue we saw in last playthrough.
=> Combat improvements

assets/first_party/music/Threadbare Loop_Main_Bridge_01.ogg.import, assets/first_party/music/Threadbare Loop_Main_Bridge_02.ogg.import, assets/first_party/music/Threadbare Loop_Main_Cresendo_01.ogg.import, assets/first_party/music/Threadbare Loop_Main_Intro_01.ogg.import, assets/first_party/music/Threadbare_Bed.ogg.import, assets/first_party/music/Threadbare_Combat.ogg.import, assets/first_party/music/Threadbare_Main_Loud.ogg.import, assets/first_party/music/Threadbare_Main_Quiet.ogg.import, assets/first_party/music/Threadbare_Stealth.ogg.import
Fixes https://github.com/endlessm/threadbare/issues/391
=> Make background music loop

scenes/quests/lore_quests/quest_001/1_music_puzzle/components/xylophone/musical_rock.gd, scenes/quests/lore_quests/quest_001/1_music_puzzle/components/xylophone/musical_rock.tscn
Fixes for https://github.com/endlessm/threadbare/pull/472 that I realized after merging.
=> Musical rock fixes

scenes/ui_elements/dialogue/components/theme.tres
This was broken in commit 08c6bad048c1335a2dc20efcc248a520f75ab131.
=> dialogue theme: Fix broken reference to panel texture

scenes/game_elements/props/eternal_loom/components/eternal_loom.aseprite, scenes/game_elements/props/eternal_loom/components/eternal_loom_blue.png, scenes/game_elements/props/eternal_loom/components/eternal_loom_green.png, scenes/game_elements/props/eternal_loom/components/eternal_loom_purple.png, scenes/game_elements/props/eternal_loom/components/eternal_loom_red.png, scenes/game_elements/props/eternal_loom/components/eternal_loom_yellow.png, scenes/game_elements/props/eternal_loom/eternal_loom.tscn
Fixes https://github.com/endlessm/threadbare/issues/539
=> Eternal Loom: replace static image for animation

scenes/world_map/frays_end.tscn
Some NPCs weren't children of the NPCs node, and there was a tree that was a child of another tree. Fixed those cases.
=> Fray's end: fix nodes' parents

project.godot, scenes/game_elements/characters/player/components/player_fighting.gd, scenes/game_elements/fx/shaker/Shaker.tscn, scenes/game_elements/fx/shaker/components/shaker.gd, scenes/game_elements/fx/shaker/components/shaker.gd.uid, scenes/globals/camera_shaker/CameraShake.tscn, scenes/globals/camera_shaker/camera_shake.gd, scenes/globals/camera_shaker/camera_shake.gd.uid
=> Add camera shake when hit in combat

scenes/game_elements/props/decoration/hiding_mushroom/hiding_mushroom.gd, scenes/game_elements/props/decoration/hiding_mushroom/hiding_mushroom.tscn, scenes/world_map/frays_end.tscn
Fix https://github.com/endlessm/threadbare/issues/580
=> Hushrooms flip behavior

scenes/quests/story_quests/template/0_intro/intro.dialogue
Adjust intro placeholder dialogue to better match learner StoryQuest contributor workflow.
=> Adjust intro template placeholder dialogue 

icon.png
Replace the placeholder with a new icon.
Fixes https://github.com/endlessm/threadbare/issues/623
=> New project icon

scenes/eternal_loom_sokoban/levels/eternal_loom_template.tscn, scenes/eternal_loom_sokoban/levels/sokoban_level_1a.tscn, scenes/eternal_loom_sokoban/levels/sokoban_level_1b.tscn, scenes/eternal_loom_sokoban/levels/sokoban_level_1c.tscn, scenes/eternal_loom_sokoban/levels/sokoban_level_2a.tscn, scenes/eternal_loom_sokoban/levels/sokoban_level_2b.tscn, scenes/eternal_loom_sokoban/levels/sokoban_level_2c.tscn, scenes/eternal_loom_sokoban/levels/sokoban_level_3a.tscn, scenes/eternal_loom_sokoban/levels/sokoban_level_3b.tscn, scenes/eternal_loom_sokoban/levels/sokoban_level_3c.tscn
This is the same loop as Fray's End, which makes conceptual sense since
the Loom is in Fray's End.
Fixes  https://github.com/endlessm/threadbare/issues/513
=> Sokoban: Add BackgroundMusic

scenes/game_elements/characters/enemies/guard/guard.tscn
This is mostly due to commit a668de8e5eee52d0f49a28a044f50cd4b29da5d1 ("Fix misplaced sound assets").
=> Guard: Update resource paths

scenes/game_elements/characters/enemies/guard/components/guard.gd, scenes/game_elements/characters/enemies/guard/guard.tscn, scenes/game_elements/characters/enemies/throwing_enemy/components/throwing_enemy.gd, scenes/game_elements/characters/enemies/throwing_enemy/throwing_enemy.tscn, scenes/game_elements/props/projectile/components/projectile.gd, scenes/quests/lore_quests/quest_001/2_ink_combat/ink_combat_round_1.tscn, scenes/quests/lore_quests/quest_001/2_ink_combat/ink_combat_round_2.tscn, scenes/quests/lore_quests/quest_001/2_ink_combat/ink_combat_round_3.tscn, scenes/quests/lore_quests/quest_001/3_stealth_level/stealth_level.tscn, scenes/quests/story_quests/template/2_template_combat/template_combat.tscn
I know that ideally the 1st commit should be split. But I ran out of time today. I can do it tomorrow!
Fixes https://github.com/endlessm/threadbare/issues/597
=> Template mute sounds

scenes/game_elements/props/collectible_item/components/collectible_item.gd
=> Don't reset collectible sprite texture every frame

scenes/globals/settings/settings.gd
While doing #9 I checked the current settings being saved, and wanted to improve the prints.
=> Settings: Revisit prints

scenes/menus/storybook/components/template_quest.tres
Fixes https://github.com/endlessm/threadbare/issues/692
=> Template: Hint that it should be used in the editor

README.md
=> README: add description and expand get-involved section

assets/first_party/logo/threadbare-logo.png.license
This logo was created in Midjourney by Joana Filizola.
=> Logo: Cite use of Midjourney

scenes/game_elements/characters/enemies/guard/components/guard.gd, scenes/game_elements/characters/enemies/guard/guard.tscn
Helps https://github.com/endlessm/threadbare/issues/680
=> Guard refactor

README.md
Fixes https://github.com/endlessm/threadbare/issues/231
=> README: Document Git LFS requirement briefly

.pre-commit-config.yaml
Kind of on the fence about this one but the output seems quite easy to understand.
=> pre-commit: Enforce editorconfig rules

scenes/game_logic/talk_behavior.gd
Follow up of https://github.com/endlessm/threadbare/issues/950
=> Talk behavior followup

scenes/game_elements/characters/enemies/guard/components/guard.gd, scenes/loader.tscn
Fix https://github.com/endlessm/threadbare/issues/976
=> Fix EditorInterface parse error bug

scenes/game_elements/props/area_filler/components/area_filler_test.tscn
I did not mean to include these; and the instructions in the scene suggest that the user should try adding rocks.
=> Remove rocks from AreaFiller test screen

scenes/world_map/frays_end.tscn
This PR just tidies up the Fray's End scene tree a little bit, in anticipation of work on the NPCs in this scene, but also to make it a bit more exemplary - as the first scene of the game it's likely that people will explore it in the editor.
There should be no in-game changes as a result of this PR.
=> Clean up Fray's End scene tree

org.endlessaccess.threadbare.yml
=> Flatpak: Inhibit screensaver, use Wayland

docs/screenshot.png, linux/metainfo.xml
=> Refresh AppStream metainfo

README.md
I'm leaving this in draft until the app is marked as verified.
=> README: Link to Flathub

scenes/globals/scene_switcher/scene_switcher.gd
Previously, Fray's End could be reached from any of the following URL hashes:
- `#world_map/frays_end`, which is what the game sets
- `#res://scenes/world_map/frays_end.tscn`, the full canonical path to the scene, which is perhaps the easiest to copy in the editor's FileSystem view
- `#world_map/frays_end.tscn`, which I don't imagine anyone will ever use
- `#res://scenes/world_map/frays_end`, ditto
- `#uid://cufkthb25mpxy`, which I use but I don't think anyone else does
However `scenes/world_map/frays_end` and
`scenes/world_map/frays_end.tscn` were not previously accepted: either you had to include the full `res://scenes/` prefix, or omit it all. But `scenes/world_map/frays_end.tscn` is the easiest thing to copy from the command-line or from GitHub.
Accept paths that begin with `scenes/`, …
=> scene_switcher: Allow relative paths without res:// prefix

project.godot, scenes/quests/story_quests/template/2_template_combat/template_combat.tscn
Move the targets on the template quest scenario to avoid getting stuck.
Fix https://github.com/endlessm/threadbare/issues/701
=> Fix getting stuck behind targets in template combat level

icon-256.png, icon.aseprite, icon.png
This colour is the darker green from the grass, with the V of its HSV halved from 61 to 30.
https://github.com/endlessm/threadbare/issues/1158
----
=> icon: Replace black border with dark green

scenes/game_elements/characters/components/gym_area_test.tscn, scenes/game_logic/character_animation_player_behavior.gd, scenes/game_logic/character_animation_player_behavior.gd.uid, scenes/game_logic/character_sprite_behavior.gd
Resolve https://github.com/endlessm/threadbare/issues/1225
=> Add AnimationPlayer version of CharacterSpriteBehavior

AUTHORS
Keep lines sorted alphabetically.
=> AUTHORS: Add shjourney authors to file

scenes/game_elements/characters/enemies/throwing_enemy/components/throwing_enemy.gd
Resolves https://github.com/endlessm/threadbare/issues/1122
=> Projectile settings

export_presets.cfg
This is just the result of exporting the project in Godot 4.5.
=> export_presets: Update with Godot 4.5 options
